### ISSUE TITLE
Provide SEAL API

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#10]
### Context
The goal of TenSEAL isn't to wrap SEAL and make it available to use in Python but as we have everything setup to make a full port of it to Python (making every cpp object and API call available through python), I think that it would be nice to make a tenseal.seal_api submodule that do this.

### TODO
- Bind all SEAL objects (providing access to all their methods and public attributes), preferably done in a separate file `sealapi.cpp` under `tenseal/`.
- Customize the build (`setup.py` and `CMakeLists.txt`) to make the build of the SEAL API optional.

**Comment by bcebere** [comment]
I would like to work on this, if it not already assigned/resolved.

**Comment by youben11** [comment]
Thanks @bcebere ! PM me on slack if you need further details
