### ISSUE TITLE
About the saving and loading of tenseal data and keys.

### ISSUE THREAD

**Issue by linjinchang** [OpenMined/TenSEAL#107]
I use tenseal directly
context = ts.context(ts.SCHEME_TYPE.CKKS, 8192, coeff_mod_bit_sizes=[60, 40, 40, 60])
ckks_vec = ts.ckks_vector(context, plain_vec, scale)
Q：How to save and load the secret_key、public_key、relin_keys and the ckks_vec in the context to a local file?

**Comment by bcebere** [comment]
Hello.

For the context, you can use 

```    
//write ctx_buff to file, socket etc.
ctx_buff = context.serialize()

//read ctx_buff from file, scoket
tenseal.context_from(ctx_buff)```


For the vectors, we'll add support later this week, I hope that works for you. 
After that, you'll be able to save the full vector to bytes and recreate it.

**Comment by youben11** [comment]
Adding to what Bogdan explained, saving a context will also save the keys, so if you hadn't dropped the secret-key in your context, restoring the context from the buffer should also restore the secret-key
