### ISSUE TITLE
Automate build-push to PyPI

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#11]
As TenSEAL includes a binary extension, it needs some extra attention on the build process to support different platforms, but the ideal would be to have this process automated on release, so whenever a new version comes in, it gets built and pushed to [PyPI](https://pypi.org/).

### Some resources

- https://github.com/pypa/manylinux
- https://packaging.python.org/tutorials/packaging-projects/
- https://packaging.python.org/guides/packaging-binary-extensions/
- https://packaging.python.org/specifications/platform-compatibility-tags/

**Comment by karlhigley** [comment]
[`scikit-build`](https://scikit-build.readthedocs.io/en/latest/) looks promising, since it wraps CMake and setuptools, which the project is already using.

**Comment by youben11** [comment]
Current build for MacOS only supports the latest version (Catalina), that's the only available environment on github actions. Karl suggested to look at [Travis](https://docs.travis-ci.com/user/reference/osx/#macos-version) as it might support older versions.
