### ISSUE TITLE
Parameter what's stored while serializing the context

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#130]
## Description
API for serialization can use some parametrization. Some examples based on a client/server use case need to save the context without secret-key, galois-keys ...

```python
ctx.serialize(save_sk=False)
```

This will not save the secret key even if the context holds it, without removing the secret key from the ctx object. Without such API, someone will need to first remove the secret-key by calling `.make_context_public()` then serialize, but he can also want to use the full context with a secret-key later on.

**Comment by IanQS** [comment]
How urgent is this? I'd like to take a stab at it but I'm not sure when I can have this done

**Comment by youben11** [comment]
Not really urgent, this require some changes in how protobuff is serializing the context, I think @bcebere can give more details on this.

**Comment by bcebere** [comment]
If I'm understanding this correctly, sometimes you want to save only the public part of a context anyway, right? Not just when the context is public. 
If so, a parameter to the serialize method should do the job, the protobuf logic is already split in public and private protos.

**Comment by youben11** [comment]
Not only the secret-key, but the ability to ask for saving or not all the possible keys (galois_keys ...), I had a specific use case where I needed to save without the secret-key, but also didn't want to drop the secret-key from my context, and I expect other users to find it useful to be able to choose what to save, someone might maybe need to save only the public-key, or the public-key and galois-keys without relin-keys, etc.

**Comment by IanQS** [comment]
Would you say that the specs for this ticket have been fleshed out? If not what else should we nail down before proceeding?

**Comment by youben11** [comment]
It can be summarized as giving some optional parameters to the user to save whatever he wants to during context serialization
