### ISSUE TITLE
Need a way to check if a key is available

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#131]
## Description
If someone needs to check if galois_keys are present in a context, he will need to do that in a try except since accessing that attribute will throw an error if the keys doesn't exist. We need a flexible way to check a boolean or something to know if a key is available )

## Additional Context

Here is how the error looks in the interpreter, where ctx is a TenSEALContext

```python
>>> ctx.galois_keys()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: the current context doesn't hold a Galois keys
```

**Comment by IanQS** [comment]
C++, right? I can take this on

**Comment by youben11** [comment]
Thanks :)

**Comment by IanQS** [comment]
This is a public-facing function, correct? The user would conceivably do something like

```
if ctx.has_galois_keys():
    gk = ctx.galois_keys()
else: 
    ctx.generate_galois_keys()
    ctx.galois_keys()
```

? 


Assuming I understand the task correctly this should just amount to 

```
bool TenSEALContext::has_galois_key() const {
    if (this->_galois_keys == nullptr){
        return false;
    }
    return true;
}
``` 

Within `tensealcontext.cpp`, right? (and the appropriate header, of course)

**Comment by youben11** [comment]
Exactly, we may also need another one for relin_keys
