### ISSUE TITLE
CKKSTensor - Batching

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#159]
## Feature Description
A tensor of shape (batch_size, height, width, depth) should be stored in an encrypted tensor of shape (height, width, depth) where the batch_size dimension should be batched across ciphertexts. We shouldn't allow the user to customize which axis need to be batched, but we leave the responsibility of reshaping it with the batch_axis as the first dimension to the user.

The API should looks something like this, with `batch` specifying if we should batch the first dimension or not
`tenseal.ckks_tensor(context, plain_tensor, batch=True)`

## What alternatives have you considered?
We could allow the user to specify the batch_axis, but I guess this will add complexity to the code. And specifying an input tensor format to the user shouldn't be an issue.

**Comment by bcebere** [comment]
I can work on this one
