### ISSUE TITLE
How can I send public key to another client, so it can encrypt its data?

### ISSUE THREAD

**Issue by Coldfire93** [OpenMined/TenSEAL#188]
I have two clients-client A and client B. Client A has both public key and private key. Client A sends public key to client B, so client B can encrypt its data, and send the encrypted data to client A. Client A use the private key to decode the encrypted data from client B. 
My question is :
1) How to send the public key to client B? ( I tried to write the public key into a file, but it can not be serialized（I used pickle).)
2) How does client B encrypt its data? I can't find the proper function that I can call to do this thing.( Like the following code, ts.bfv_vector(), the first argument is context, but the TenSEALContext object holds both public key and private key. It's obvious that client B is not allowed to get the private key in this application scenario.)
`import tenseal as ts`
`context = ts.context(ts.SCHEME_TYPE.BFV, poly_modulus_degree=4096, plain_modulus=1032193)`
`a = np.array([1, 2, 3])`
`enc_a = ts.bfv_vector(context, a)`
`enc_a.decrypt()`
3) The decrypt() function has no arguments. I'm curious how the decryption is performed. If enc_a is send to client B, client B has no private key, can client B get the decrypted result just by calling the decrypt() function?

Thank you very much.

**Comment by youben11** [comment]
Hi @Coldfire93

1. You can send the context which contain the public key by calling `context.serialize()` which will return bytes. We don't support pickle. Make sure to call `context.make_context_public()` before doing that, in order to drop the secret_key from the context.
2. The tensor constructor methods all use the public key for encryption and you don't need to call encrypt explicitly. The context doesn't need to hold the secret key in order to encryption to happen, but only the public key.
3. The decrypt() function doesn't need an argument as long as its linked context (that was passed during tensor creation) holds a secret key. If that's not the case (`context.make_context_public()` was called previously, thus dropping the secret key), the decrypt function must take the secret key as argument.

**Comment by Coldfire93** [comment]
> Hi @Coldfire93
> 
> 1. You can send the context which contain the public key by calling `context.serialize()` which will return bytes. We don't support pickle. Make sure to call `context.make_context_public()` before doing that, in order to drop the secret_key from the context.
> 2. The tensor constructor methods all use the public key for encryption and you don't need to call encrypt explicitly. The context doesn't need to hold the secret key in order to encryption to happen, but only the public key.
> 3. The decrypt() function doesn't need an argument as long as its linked context (that was passed during tensor creation) holds a secret key. If that's not the case (`context.make_context_public()` was called previously, thus dropping the secret key), the decrypt function must take the secret key as argument.

@youben11 
Thank you ! 🙏  Your answer is very clear. The only thing I'm confused is the serialize() function. Can you explain it ? Because I can not call it directly.

**Comment by bcebere** [comment]
Hi @Coldfire93 

You can find serialization examples for TenSEAL in the tests folder:
 - [Context serialization examples](https://github.com/OpenMined/TenSEAL/blob/master/tests/python/tenseal/test_serialization.py)
 - [Tensors serialization examples](https://github.com/OpenMined/TenSEAL/blob/master/tests/python/tenseal/tensors/test_serialization.py)

You can see the `serialize` method in actions there.

**Comment by Coldfire93** [comment]
> Hi @Coldfire93
> 
> You can find serialization examples for TenSEAL in the tests folder:
> 
> * [Context serialization examples](https://github.com/OpenMined/TenSEAL/blob/master/tests/python/tenseal/test_serialization.py#L25)
> * [Tensors serialization examples](https://github.com/OpenMined/TenSEAL/blob/master/tests/python/tenseal/tensors/test_serialization.py#L56)
> 
> You can see the `serialize` method in action there.
@bcebere 
Thank you for your answer. But I got the error "AttributeError: '_tenseal_cpp.TenSEALContext' object has no attribute 'serialize'" when I call ctx.serialize(). I wonder if the reason that I got the error is that when I import tenseal, I got the error "AttributeError: module '_tenseal_cpp' has no attribute 'im2col_encoding' ". 
The position the error produced is in the following code:
tenseal/__init__.py 
`im2col_encoding = _ts_cpp.im2col_encoding`

**Comment by bcebere** [comment]
Can you tell us what TenSEAL version do you use and on what platform? Thank you.

**Comment by Coldfire93** [comment]
@bcebere 
tenseal             0.1.0
OS:      macOS 10.15.6
Thank you.

**Comment by bcebere** [comment]
@Coldfire93 
Yes, you are right, the version with serialization support isn't marked as stable yet.
The serialization was introduced in v0.2.0.

You can checkout the latest version, because we fixed several other bugs.
```
pip install tenseal==0.3.0a1
```

Please let us know if that fixes your problem.

**Comment by Coldfire93** [comment]
@bcebere 
I installed the version you specified, and the serialize() method runs correctly.
Thank you very much. 🙏

**Comment by Coldfire93** [comment]
@bcebere 
I have another question.
I noticed that the tenseal version you provide for Linux platform is Linux 64bit. Will you provide the tenseal version for Linux 32 bit ?

**Comment by Coldfire93** [comment]
@bcebere 
I have another question.
I noticed that the tenseal version you provide for Linux platform only supports Linux 64bit. Will you provide the tenseal version for Linux 32 bit ?

**Comment by bcebere** [comment]
We don't have that in plan since there aren't many distros left that support 32bit.

But if you have a use case, please open a separate issue, and document the scenario/target platform, and we will have a look.

**Comment by Coldfire93** [comment]
@bcebere 
I see. Thanks a lot. 😊
