### ISSUE TITLE
SyFT -- TenSeal troubles

### ISSUE THREAD

**Issue by vivoutlaw** [OpenMined/TenSEAL#19]
Hi, nice work!

I came across your tutorial of HE usage via syft. [https://blog.openmined.org/ckks-homomorphic-encryption-pytorch-pysyft-seal/](https://blog.openmined.org/ckks-homomorphic-encryption-pytorch-pysyft-seal/)

Can you please let me know, how can I import this "import syft.frameworks.tenseal as ts" as tenseal seems to unavailable in syft.frameworks? Thanks

best, Vivek

**Comment by youben11** [comment]
Hi Vivek ! Thanks for trying the demo. The branch the demo is working on isn't the master, and we expect to merge it soon so that you can try it directly on master.

And keep in mind that importing syft.frameworks.tenseal isn't the same as importing tenseal, it is integrated into PySyft in a different way to adapt it to the framework.

**Comment by vivoutlaw** [comment]
Yep, please let me know when you release the merge. Thanks again!

Btw, just found out that. If you try to encrypt a vector for more than 4100 elements.  Tenseal throws RuntimeError: values_matrix size is too large

import tenseal as ts
import numpy as np
context = ts.context(ts.SCHEME_TYPE.BFV, poly_modulus_degree=4096, plain_modulus=1032193)
plain_vector = np.arange(4100)
encrypted_vector = ts.bfv_vector(context, plain_vector)

**Comment by youben11** [comment]
Yeah, so we now use a single ciphertext for batching vector elements, which means that you can store up to poly_modulus_degree elements in BFV and up to the half of poly_modulus_degree for CKKS. This will hopefully improve in the near future as we are still experimenting which structure for tensors works best.

You can keep an eye on OpenMined/PySyft#3321 which will merge the CKKSTensor on master.

**Comment by macknight** [comment]
has this been resolved? 

BR
