### ISSUE TITLE
Reshaping CKKSTensor

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#192]
## Feature Description
We want to reshape our tensors, without any memory copy, but using the strided view we already have internally.

## Affected Dependencies
This will have an impact on the currently implemented element-wise operations. They are only iterating over the internal storage, however, different shapes require a different iteration.

## Is your feature request related to a problem?
Future features might hardly depends on the shape of the tensor.

## Additional Context
Element-wise operations of different shape might need an iterator that traverses dimensions one by one in order to yield the same order of elements for element-wise operations.

**Comment by bcebere** [comment]
I can work on this one.
