### ISSUE TITLE
Lazy loading of TenSEALContext

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#193]
## Feature Description
When an Encrypted Tensor is deserialized, it need to be linked to a TenSEALContext to be operational, and that's why we require the context to be passed during deserialization. However, we can deserialize without the TenSEALContext, setting the tensor to be non functional, then requiring to link it to a specific context later to make it functional.

## Is your feature request related to a problem?
We often expect the serialized output to be deserialized as is, without requiring extra information.

**Comment by bcebere** [comment]
I can work on this one.
