### ISSUE TITLE
Implementing Set Intersection

### ISSUE THREAD

**Issue by jatanloya** [OpenMined/TenSEAL#195]
## Question
How do I implement private set intersection using TenSEAL?

## Further Information
Is there an inbuilt feature available or a way to implement PSI using TenSEAL?

## System Information
 - OS: macOS Catalina
 - OS Version: 10.15.7
 - Language Version: Python 3.7

**Comment by bcebere** [comment]
Hello.

First of all, there is a dedicated implementation for PSI [here](https://github.com/OpenMined/PSI/tree/master/private_set_intersection).

If you want a solution over SEAL, there is one [here](https://github.com/OpenMined/PIR), using Private Information Retrieval.

If you want to use TenSEAL for that, we don't provide an implementation in the library. One inefficient solution would be to encrypt each value in your set as a ciphertext, subtract everything from the server database to each ciphertext, and then multiply all results. If the product is zero, then the intersection is non-empty.

But the PSI repository offers a better solution here.

**Comment by jatanloya** [comment]
Helo, thanks for the quick help.
I wanted something that runs over SEAL so the PIR link is quite helpful. I'll head there and try to customize it.
Thanks Again.
