### ISSUE TITLE
FHE operations on CUDA

### ISSUE THREAD

**Issue by bcebere** [OpenMined/TenSEAL#20]
Hello, 

Just wondering, have you considered using a FHE library with CUDA support? Could they bring some benefits? 

Some examples are 
https://github.com/vernamlab/cuFHE
and 
https://github.com/nucypher/nufhe

**Comment by youben11** [comment]
Hi @bcebere , those two library you mentioned are implementing the TFHE scheme which support homomorphic boolean gates, I don't know of any (good) library implementing CKKS with CUDA support, let me know if there is. But it might be interesting to explore implementing boolean vectors with these two libraries if we can think of a use-case for them.

**Comment by iamtrask** [comment]
Note - the (under development) port of FV to PyTorch will run on CUDA.

**Comment by Geremia** [comment]
@iamtrask What's FV? BFV? What's the name of the repo?
