### ISSUE TITLE
CKKSTensor creation: parallel encryption

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#200]
## Description
Current tensor creation encrypts elements in a single thread by iterating over them, however, a more efficient way to do this is to run different threads that will encrypt a subset of the elements.

Better done after: #202 

## Additional Context
We already have a threadpool implementation, we only need to refactor the code to use that.

**Comment by CerineBnsd** [comment]
Hello ! if this issue is still available, can you assign it to me ?
