### ISSUE TITLE
Only a finite number of computations can be performed on ciphertext. Is there any way to perform as many computations as possible?

### ISSUE THREAD

**Issue by Coldfire93** [OpenMined/TenSEAL#204]
After about 3-4 computations, I have to decrypt it, then encrypt it, then compute it. 

Since the decryption can only be performed on the side(client A) which has secret key, the encrypted intermediate results produced by client B have to be sent to A to decrypt and encrypt again.

Is there any way to perform as many computations as possible? (Even if 1-2 computations more)

Thank you!

**Comment by youben11** [comment]
You can increase the depth of your computation, by increasing the parameters you are using, at the cost of performance.

**Comment by Coldfire93** [comment]
> You can increase the depth of your computation, by increasing the parameters you are using, at the cost of performance.

OK. Thank you~

**Comment by bcebere** [comment]
While we want do integrate a HE compiler in TenSEAL too, you can simulate your operations using [Microsoft EVA](https://github.com/microsoft/EVA) and generate optimal parameters for your scenario.
