### ISSUE TITLE
Why does increasing the global_scale parameter not work?

### ISSUE THREAD

**Issue by Coldfire93** [OpenMined/TenSEAL#205]
We tested the following code. And we found that  the multiply computation can only be executed correctly twice.
We increase the global_scale parameter from pow(2, 40) to pow(2, 60), but it does not solve the problem.
I was wondering if you could tell me the reason? Thank you~

`import tenseal as ts

context = ts.context(
            ts.SCHEME_TYPE.CKKS,
            poly_modulus_degree=8192,
            coeff_mod_bit_sizes=[60, 40, 40, 60]
          )
context.generate_galois_keys()
context.global_scale = 2**40

v1 = [0, 1, 2, 3, 4]
v2 = [4, 3, 2, 1, 0]

enc_v1 = ts.ckks_vector(context, v1)
enc_v2 = ts.ckks_vector(context, v2)

result = enc_v1 + enc_v2
result.decrypt() # ~ [4, 4, 4, 4, 4]

for i in range(3): # for i in range(3) ==> "scale out of bounds";   range(2)==>OK
    result = result.mul(enc_v2)

print(result.decrypt()) #

**Comment by bcebere** [comment]
The scale is affected by the polynomial modulo and coefficient modulo too.
Using
``` poly_modulus_degree=16384,
 coeff_mod_bit_sizes=[60, 40, 40, 40, 40, 40, 60]
```
will work for you.

In case of "scale out of bounds", usually you have to increase coeff_modulus, adn with that, sometimes poly_modulus too.

That's why I was saying that HE needs a dry run first, to figure out the right parameters for the computation. If you have any suggestions here - about the usability or something else - please leave an issue. We are still brainstorming how to automate parameter selection, and your input would be pretty useful.

 Thank you!

**Comment by youben11** [comment]
put another way, you can know how much mul you can perform from the `len(coeff_mod_bit_sizes)`, it's actually `len(coeff_mod_bit_sizes) - 2`. Your scale then need to match the number of bits in the middle coefficients (here 40, so scale=2**40).

**Comment by Coldfire93** [comment]
> The scale is affected by the polynomial modulo and coefficient modulo too.
> Using
> 
> ```
> poly_modulus_degree=16384,
> coeff_mod_bit_sizes=[60, 40, 40, 40, 40, 40, 60]
> ```
> 
> will work for you.
> 
> In case of "scale out of bounds", usually you have to increase coeff_modulus, adn with that, sometimes poly_modulus too.
> 
> That's why I was saying that HE needs a dry run first, to figure out the right parameters for the computation. If you have any suggestions here - about the usability or something else - please leave an issue. We are still brainstorming how to automate parameter selection, and your input would be pretty useful.
> 
> Thank you!

Thank you for your reply. I understand. 👍

**Comment by Coldfire93** [comment]
> put another way, you can know how much mul you can perform from the `len(coeff_mod_bit_sizes)`, it's actually `len(coeff_mod_bit_sizes) - 2`. Your scale then need to match the number of bits in the middle coefficients (here 40, so scale=2**40).

Thank you, I understand. 👍
