### ISSUE TITLE
Example of multiplication between encrypted matrix and plaintext vector

### ISSUE THREAD

**Issue by jbzhang1** [OpenMined/TenSEAL#207]
Hi,

I was wondering if there are examples of multiplication between an encrypted matrix (CKKSVector) and plaintext vector.

**Comment by youben11** [comment]
Hi @jbzhang1, we often have tests for the features we provide that you can use as a reference, and there is a test [here](https://github.com/OpenMined/TenSEAL/blob/ea8f04f7bb8b262dacb0dbd00f896b5d30ba57ad/tests/python/tenseal/tensors/test_ckks_vector.py#L1015) running this use case of yours.
