### ISSUE TITLE
Polyval upto x^3 (multiplied-ciphertext) getting 'scale out of bounds' error

### ISSUE THREAD

**Issue by qiminghe** [OpenMined/TenSEAL#216]
## Description
polyval (upto x^3) works for cipher_text directly encrypted plain_text and additions, but does not work after multiplying plain/cipher_text.  Getting "ValueError: scale out of bounds".
polyval (upto x^2) works with all cases.

## How to Reproduce
import numpy      as np 
import tenseal    as ts 
context = ts.context(ts.SCHEME_TYPE.CKKS,poly_modulus_degree=8192,coeff_mod_bit_sizes=[60, 40, 40, 60])
context.generate_galois_keys()
context.global_scale = 2**40 
x=np.random.rand(10); 
crypt_x = ts.ckks_vector(context, x)
#works per https://github.com/OpenMined/TenSEAL/blob/master/tutorials/Tutorial%200%20-%20Getting%20Started.ipynb
crypt_x.polyval([0.5, 0.197, 0, -0.004]) 
crypt_y = crypt_x + 1  		# works after 'adding' plaintext
crypt_z = crypt_y.polyval([0.5, 0.197, 0, -0.004]) 
crypt_y = crypt_x + crypt_x	# works after 'adding' ciphertext
crypt_z = crypt_y.polyval([0.5, 0.197, 0, -0.004]) 
crypt_y = crypt_x * 2     	# does not works after 'multiply' plaintext 
crypt_z = crypt_y.polyval([0.5, 0.197, 0, -0.004]) 
w=np.random.rand(10,10); 
crypt_y = crypt_x.matmul(w)	#does not work either
crypt_z = crypt_y.polyval([0.5, 0.197, 0, -0.004]) 
crypt_z = crypt_y.polyval([0.5, 0.197, 1]) #works if only use x^2 poly

## Expected Behavior
polyval(.) should work for all ciphertext (after add/mul) at least upto x^3. 
If context has to be reset,  please give a direction how to do so, in case of x^3, x^4, ....

## System Information
python: 3.8.3 on ubuntu
print (ts.__version__) : 0.1.0

**Comment by bcebere** [comment]
Hello.

On a first look, it works if you increase poly_modulus_degree
```ts.context(ts.SCHEME_TYPE.CKKS,poly_modulus_degree=16384, coeff_mod_bit_sizes=[60, 40, 40, 40, 60])```

But I am not entirely sure why it is failing in your scenario. I will have a look at that in the following days.

**Comment by qiminghe** [comment]
Thanks for quick response. I tried 16384, even 32768. Does NOT help. 
If anyone wants to approximate a non-linear activation function (as seen in ML) by poly, order x^3 should be the minimal to ask :-) Also we cannot assume input data are all directly encrypted plaint-text, e.g., in a multi-layered NN.

**Comment by bcebere** [comment]
the snippet above doesn't work with 16384? what error do you get? I just tried it and it is OK.

**Comment by bcebere** [comment]
Also, while it is not marked as stable, I recommend using 
```pip install tenseal==0.3.0a1```

since we made several improvements since 0.1.0.

We will release another stable version soon.

**Comment by qiminghe** [comment]
re-tried with 0.3.0a1. Same error. See SS. [
![tenseal-0 3 0a1](https://user-images.githubusercontent.com/4943625/104959680-bd453180-59a0-11eb-9e01-1608daf7d36c.PNG)
](url)

**Comment by bcebere** [comment]
My bad, I forgot to mention, in the context above I change bit_sizes as well, not just the poly_mod.

```
ts.context(ts.SCHEME_TYPE.CKKS,poly_modulus_degree=16384, coeff_mod_bit_sizes=[60, 40, 40, 40, 60])
```

coeff_mod_bit_sizes is [60, 40, 40, 40, 60] in my example.

**Comment by qiminghe** [comment]
Thanks a lot. works for both versions. coeff_mod_bit_sizes is the key.  
I am assuming if I am going upto x^4 or higher, I just need to expand coeff_mod_bit_sizes in format [60, 40, 40, 40, ..., 60].

**Comment by bcebere** [comment]
You don't have to expand coeff_mod_bit_sizes for every degree; there is a limit in SEAL anyway for their length/sum.

We have some tests for higher degree polynomials scenario here https://github.com/OpenMined/TenSEAL/blob/master/tests/python/tenseal/tensors/test_ckks_vector.py#L1113

As you can see, [60, 40, 40, 40, 40, 40, 60] should do the job for higher polynomials, but be careful with the precision.

**Comment by youben11** [comment]
For computing polyval for a polynomial of degree N, your parameters need to support 'round_up(log2(N))' So x^3 already requires 2 multiplication, multiplying the result after the polynomial evaluation will require thus require 3 multiplications. If your parameters can't support the required number of multiplications, you will get a scale out of bound error after the last allowed multiplication

**Comment by qiminghe** [comment]
Just got more 

x=np.random.rand(10); 
crypt_x = ts.ckks_vector(context, x)
w=np.random.rand(10,10); 
crypt_y = crypt_x.matmul(w)	
crypt_z = crypt_y.polyval([0.5, 0.197, 0, -0.004])  #works with advised coeff_mod_bit_sizes settings
output = crypt_z.matmul(w) # After polyval is crypt_
#However, when
0.1.0>>> output = crypt_z.matmul(w)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: scale out of bounds

**Comment by youben11** [comment]
I assume your CKKS context supports 3 multiplications only (e.g. coeff_mod_bit_sizes=[60, 40, 40, 40, 60]), so the forth did throw the error.

**Comment by qiminghe** [comment]
Not sure my last comment (after issue was closed) become visible. Just reopen and recap:
After we do polyval, can we multiply a plaintext vector with it? i.e.,
crypt_z = crypt_y.polyval([0.5, 0.197, 0, -0.004]) 
output = crypt_z.matmul(w) 
I am getting different error from 0.1.0 and 0.3.0 for the above operation.

**Comment by bcebere** [comment]
Hello.

Can you provide the full script that is failing now? Just to be sure about crypt_y's value.

**Comment by qiminghe** [comment]
Sure. Test script is simply generating a vector/matrix of random numbers, and do func_poly( enc(x) *w) * w
==========
import numpy      as np 
import tenseal    as ts 
context = ts.context(ts.SCHEME_TYPE.CKKS,poly_modulus_degree=16384,coeff_mod_bit_sizes=[60, 40, 40, 40, 60])
context.generate_galois_keys()
context.global_scale = 2**40 
x=np.random.rand(10); 
crypt_x = ts.ckks_vector(context, x)
w=np.random.rand(10,10); 
crypt_y = crypt_x.matmul(w)	
crypt_z = crypt_y.polyval([0.5, 0.197, 0, -0.004]) 
output = crypt_z.matmul(w)

**Comment by bcebere** [comment]
Thank you for reporting this.

The error you are receiving is not meaningful at all, and we will fix that, to forward the actual error. I opened https://github.com/OpenMined/TenSEAL/issues/217.

The actual error that is wrapped by std::exception is
```
ValueError: scale out of bounds
```

This can be fixed by expanding coeff_mod_bit_sizes 

```
 context = ts.context(ts.SCHEME_TYPE.CKKS,poly_modulus_degree=16384,coeff_mod_bit_sizes=[60, 40, 40, 40, 40, 60])
```

**Comment by napoay** [comment]
I encountered the same error:

```
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_2(enc_x):
    return enc_x.polyval([0.5, 0.197, 0, -0.004])

w1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
b1 = np.array([0.1, 0.2, 0.3])

w2 = np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])
b2 = np.array([0.1, 0.2])

w3 = np.array([[0.1, 0.3],[0.2, 0.4]])
b3 = np.array([0.1, 0.2])

def init_network():
    network = {}
    #network['W1'] = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
    network['W1'] = w1
    network['b1'] = b1
    network['W2'] = w2
    network['b2'] = b2
    network['W3'] = w3
    network['b3'] = b3
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'],network['W2'], network['W3']
    b1, b2, b3 = network['b1'],network['b2'], network['b3']
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = a3
    return y

network = init_network()

x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)


import tenseal as ts

context = ts.context(
            ts.SCHEME_TYPE.CKKS,
            poly_modulus_degree=32768,
            coeff_mod_bit_sizes=[60, 40, 40, 40, 40, 60]
        )

context.generate_galois_keys()
context.global_scale = 2**40

enc_x = ts.ckks_tensor(context, x.tolist())
enc_w1 = ts.ckks_tensor(context, w1.tolist())
enc_b1 = ts.ckks_tensor(context, b1.tolist())

enc_w2 = ts.ckks_tensor(context, w2.tolist())
enc_b2 = ts.ckks_tensor(context, b2.tolist())

enc_w3 = ts.ckks_tensor(context, w3.tolist())
enc_b3 = ts.ckks_tensor(context, b3.tolist())
enc_a1 = enc_x.dot(enc_w1) + enc_b1

enc_z1 = sigmoid_2(enc_a1)
enc_a2 = enc_z1.dot(enc_w2) + enc_b2

enc_z2 = sigmoid_2(enc_a2)
enc_a3 = enc_z2.dot(enc_w3) + enc_b3

```

`enc_z1 = sigmoid_2(enc_a1)` can be executed correctly， But`enc_z2 = sigmoid_2(enc_a2)`  can't be executed correctly:

```
[0.31682708 0.69627909]
Traceback (most recent call last):
  File "he-nn.py", line 72, in <module>
    enc_z2 = sigmoid_2(enc_a2)
  File "he-nn.py", line 7, in sigmoid_2
    return enc_x.polyval([0.5, 0.197, 0, -0.004])
  File "/home/lcf/anaconda3/lib/python3.6/site-packages/tenseal/tensors/abstract_tensor.py", line 177, in polyval
    return self._wrap(self.data.polyval(coefficients))
ValueError: scale out of bounds
```
