### ISSUE TITLE
'Scale out of Bound' issue for several multiplication on the same ckks vector 

### ISSUE THREAD

**Issue by WestLifYan** [OpenMined/TenSEAL#241]
## Description
When I try to work out the function of matrix inversion, the error occurs when I try to perform multiplication between a ckks vector with plain text and assign the result to the same ckks vector.

## How to Reproduce
# Setup TenSEAL context
context = ts.context(
            ts.SCHEME_TYPE.CKKS,
            poly_modulus_degree=16384,
            coeff_mod_bit_sizes=[60, 40, 40,40, 60]
          )
context.generate_galois_keys()
context.global_scale = 2**40
for fd in range(1,n):
     AM_enc[fd] *= fdScaler

## Expected Behavior
No error occurs

## System Information
 - OS: Win
 - OS Version: 10
 - Language Version:Python 3.8.5
 - TenSeal Version: 0.3.0

## Additional Context
Sorry for my bad knowledge of Homomorphic Encryption, I think it may be that after multiplication, it need to rescale?

**Comment by bcebere** [comment]
Hello @WestLifYan 

What value do you use for `n` in the loop?

**Comment by WestLifYan** [comment]
Thank for reply
the n is the size of square matrix , in my case it is at least 200

**Comment by bcebere** [comment]
Is fdScaler a PlainTensor? Can you provide the full code?

**Comment by WestLifYan** [comment]
The fdScaler is Plaintext
The cold is:  

    def encMatReversion(AM):
        IM = np.identity(len(AM))
        AM_enc = []
        IM_enc = []
        for i in range(len(A)):
            AM_enc.append(ts.ckks_vector(context, AM[i]))
            IM_enc.append(ts.ckks_vector(context, IM[i]))
        n = len(AM)
        fd = 0 # fd stands for focus diagonal OR the current diagonal
        fdScaler = 1. / AM_enc[fd].decrypt()[fd]
    
        AM_enc[fd] = fdScaler * AM_enc[fd]
        IM_enc[fd] = fdScaler * IM_enc[fd]
    
        indices = list(range(n))
        for i in indices[0:fd] + indices[fd+1:]: # *** skip row with fd in it.
            crScaler = AM_enc[i].decrypt()[fd] # cr stands for "current row".
            AM_enc[i] = AM_enc[i] - crScaler * AM_enc[fd]
            IM_enc[i] = IM_enc[i] - crScaler * IM_enc[fd]
    
        for fd in range(1,n): # fd stands for focus diagonal
            fdScaler = 1.0 / AM_enc[fd].decrypt()[fd]
            # FIRST: scale fd row with fd inverse. 
            AM_enc[fd] *= fdScaler  #!!!!!!!!!!!!!!!!!!!!!Scale Out of  Bound Happens here!!!!!!!!!!!!!!!!!!!!!!!!#
            IM_enc[fd] *= fdScaler
    
            # SECOND: operate on all rows except fd row.
            for i in indices[:fd] + indices[fd+1:]: # *** skip row with fd in it.
                crScaler = AM_enc[i].decrypt()[fd] # cr stands for "current row".
                AM_enc[i] = AM_enc[i] - crScaler * AM_enc[fd]
                IM_enc[i] = IM_enc[i] - crScaler * IM_enc[fd]
            
        return IM_enc

**Comment by bcebere** [comment]
Thank you. We will investigate the issue.

**Comment by bcebere** [comment]
Hello. The noise increases even for plain operations, but at another rate. I think that is the problem in your situation.

**Comment by WestLifYan** [comment]
Thanks for pointing out. So, is it possible to perform unlimited multiplication in Tenseal ?

**Comment by bcebere** [comment]
No. CKKS and BFV are leveled schemes, meaning you can perform a limited number of encrypted operations.
For the plain operations, the noise still increases, but at a lower rate. But you cannot do unlimited operations.

**Comment by WestLifYan** [comment]
Thanks for your answer. Given the situations, can you give me a hint to make my matrix inversion function work well on Teanseal. I really like Tenseal and want to use it for my graduation project.

**Comment by bcebere** [comment]
I don't have a good answer here.

I see there was [a discussion on SEAL's issue tracker](https://github.com/microsoft/SEAL/issues/240) as well.
Just to summarize it:
 - division is not supported for CKKS, and as far as I understand, for the matrix inverse, no matter what you do, you end up with a division.
 -  [This paper](https://eprint.iacr.org/eprint-bin/getfile.pl?entry=2018/565&version=20180605:025041&file=565.pdf) provides a way to compute the inverse usinng CKKS, with some restrictions.
 
 If you find a way to do it and need extra features in TenSEAL, feel free to open a PR, and we can help you with suggestions.
