### ISSUE TITLE
BFVVector: implement mul_plain_inplace

### ISSUE THREAD

**Issue by bcebere** [OpenMined/TenSEAL#248]
## Description
Implement the mul_plain_inplace operation for BFVVector [here](https://github.com/OpenMined/TenSEAL/blob/master/tenseal/cpp/tensors/bfvvector.cpp#L293).

You can see a similar implementation in the CKKSVector class [here](https://github.com/OpenMined/TenSEAL/blob/master/tenseal/cpp/tensors/ckksvector.cpp#L321).

In order to be accepted, the PR must include:
 - [ ] The implementation of the operation.
 - [ ] C++ tests.
 - [ ] Python tests.

**Comment by alexandrumeterez** [comment]
Hello! If this is still open, can I have a go at it?

**Comment by youben11** [comment]
@philomath213 are you working on it? or can we assign @alexandrumeterez ?

**Comment by philomath213** [comment]
> @philomath213 are you working on it? or can we assign @alexandrumeterez ?

No, I'm not.
@alexandrumeterez you can refer to #257 for the required changes (implementation, binding, tests).
