### ISSUE TITLE
Subscript operator for CKKSTensor

### ISSUE THREAD

**Issue by danif93** [OpenMined/TenSEAL#259]
## Feature Description
Introduction of the subscript operator ( \_\_getitem\_\_(self, index) ) for the CKKSTensor. This should allow selecting subrows and subcolumns from a CKKSTensor.
For example:
`t = CKKSTensor(context, torch.randn(4,5))`
`rt = t[3]          # rt is equal to the last row of t`
`ct = t[: , 4]      # rt is equal to the last column of t`
`rct = t[2: , 3:]  # rct is equal to the crypted submatrix obtained from the last 2 rows and 2 columns of t`
`bt = t[ [False,False,False,True] ] # bt is equal to the last row of t`
`assert rt.shape in ([5], [1,5])    # depending on the library standards`
`assert ct.shape in ([4], [4,1])   # same comment as previous line`
`assert rt.shape==bt.shape`
`assert rct.shape==[2,2]`

## Is your feature request related to a problem?
Since CKKSTensor represents a matrix, being able to directly selecting rows and columns from that matrix is extremely useful.

## What alternatives have you considered?
I can select ciphertexts from CKKSTensor.data.data(), but being able to treat those ciphertexts as high-level objects (or building back a CKKSTensor from a sublist of ciphertexts) is not supported yet.

**Comment by alexandrumeterez** [comment]
Hello!
If this one isn't taken, can I have a go at it? I think I'll need a little help though.
