### ISSUE TITLE
Some questions about training encrypted model over encrypted data

### ISSUE THREAD

**Issue by amyzx** [OpenMined/TenSEAL#260]
## Question
Hi, I am a student learning encrypted machine learning and have read your tutorial 1.
I have several questions as follows.

1. How can I train an encrypted model among many users? 
    Assume user A, B, C submit encrypted data to the server, then the server trained 3 encrypted models. 
    If I want to integrate these encrypted models by assigning different weights to 3 models, should A, B, C have the same private and public key? 
    I guess if they have different key pairs, the encrypted models are related to 3 different key pairs, so we cannot integrate these encrypted models.

2. Can I decrypt the encrypted model trained on encrypted data? 
    I want to apply some untrained data on the un-encrypted model. 
    

3. If user A use its encrypted data to train an encrypted model, and user B wants to use A's encrypted model, does B have to encrypt its data with A's public key and also use A's private key to decrypt the encrypted inference/evaluation result?

4. Can I apply zkSNARK on the encrypted model trained on encrypted data?
    I have read some papers which use zkSNARK to verify the correctness of neural network's computation, such as  [ZEN](https://github.com/UCSB-TDS/ZEN).  They proposed some quantization techniques on the neural network, but I am not sure whether these operations still hold for an encrypted neural network.

I am looking forward to your reply! Thanks!

**Comment by youben11** [comment]
Hi @amyzx!
1. This use case will require Multi-Key Homomorphic Encryption (MKHE) which we doesn't support
2. Yeah, the model should be just a bunch on encrypted weights, you can decrypt them and apply inference, or do even more epochs of training using plain data
3. The input for the model doesn't necessarily need to be encrypted, but providing a public-key is also fine. For the result of the model, they need to be decrypted using the secret-key
4. I don't know for this

**Comment by youben11** [comment]
Doing the evaluation is just a series of computation, so let's focus on the first one. We are assuming the model weights are encrypted.
1. In the case when we first encrypt the input data with a public-key, the first operation would be performed between a ciphertext (input) and another ciphertext (weights) and yields a ciphertext.
2. In the other case, where we just input the plain input, the operation would be performed between a plaintext and a ciphertext and also yields a ciphertext.

The conclusion is that there isn't an effect on the computation itself. However, it's worth considering the fact that plaintext-ciphertext and ciphertext-ciphertext are different in terms of noise, computation times, and other metrics. Another important thing that might affect this is weather we are using a symmetric or asymmetric scheme, the latter provide both options, while the former is limited to the second option

**Comment by amyzx** [comment]
Thanks for your detailed reply! I got it!
