### ISSUE TITLE
Noise budget CKKS

### ISSUE THREAD

**Issue by comidan** [OpenMined/TenSEAL#261]
## Question
How is it possible to get the current invariant noise of a ciphertext through your python library?

## Further Information
Searching in the repo I found out about the _invariant_noise_budget_ method in the [test_evaluator.py](https://github.com/OpenMined/TenSEAL/blob/eed2a73879ad8228b7e6d70a86cfc973235ff74a/tests/python/sealapi/test_evaluator.py) file with the usage of _helper_generate_evaluator_ method in [utils.py](https://github.com/OpenMined/TenSEAL/blob/eed2a73879ad8228b7e6d70a86cfc973235ff74a/tests/python/sealapi/utils.py), but it seems to be available for _SEALContext_ and not _TenSEALContext_ which indeed brings up some incompatibilities when I try to get the noise from a CKKS encrypted tensor due to the different paramaters type required.
In details, if I call this method on an encrypted tensor I will get back an exception saying that tenseal.tensors.ckkstensor.CKKSTensor is incompatible with such method and _sealapi_cpp.Ciphertext should be used instead, but as far as I know and I may be completely wrong, this _sealapi_cpp.Ciphertext is a lower level data type of your API and so not directly obtainable starting from a tenseal.Context initialization method.

**Comment by bcebere** [comment]
Hi

Thank you for your question.

Yes, you are right, the SEAL API is in a submodule of TenSEAL, and it is not directly linked to the TenSEAL bindings.

But we will have a look and try to link them together, it is a good use case.

**Comment by bcebere** [comment]
Hi

Thank you for your question.

Yes, you are right, the SEAL API is in a submodule of TenSEAL, and it is not directly linked to the TenSEAL bindings.

But we will have a look and try to link them together, it is a good use case.

**Comment by bcebere** [comment]
@comidan This PR https://github.com/OpenMined/TenSEAL/pull/265 tries to address your question. 

Before we merge it, can you confirm if [this test](https://github.com/OpenMined/TenSEAL/blob/pybind_submodule/tests/python/tenseal/test_tensealcontext.py#L115) is similar to what you are expecting? 

Thank you!

**Comment by comidan** [comment]
> @comidan This PR #265 tries to address your question.
> 
> Before we merge it, can you confirm if [this test](https://github.com/OpenMined/TenSEAL/blob/pybind_submodule/tests/python/tenseal/test_tensealcontext.py#L115) is similar to what you are expecting?
> 
> Thank you!

Yes, I wanted indeed to monitor the noise level among operations in order to choose the best encryption paramaters in a specific case.

Just one thing, I asked about the CKKS scheme but in the test it's shown the BFV scheme usage only. If it will work as well as with CKKS tensor than yes it's ok, but I think yes because I saw the new code you wrote and it involves adding references to the CKKS tensor type as well, so I think it's a yes.

Well what I have to say, wow! Thank you and thank you for being so fast!

**Comment by bcebere** [comment]
The noise growth monitoring is possible only for the BFV scheme, using the invariant_noise_budget call.

The noise monitoring is not possible for CKKS, and SEAL doesn't support it. You can try to approximate it, but it is rarely close to the real value. However, the noise in CKKS is not an issue for decryption fails, as it is for BFV, but it affects the precision.

**Comment by comidan** [comment]
Ok I understand, thank you for the very informative link! It's very interesting and useful.

I think then that this issue is completely solved, since there is already a fix waiting for merge approval.
