### ISSUE TITLE
Slack link not working?

### ISSUE THREAD

**Issue by fboemer** [OpenMined/TenSEAL#284]
The `Click here to join our Slack community!` link from the main README as well as the `General Questions about OpenMined
` issue template both lead to a Slack website showing:

```
This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.
```
This also happens for me when I go to `https://slack.openmined.org/` directly

**Comment by cereallarceny** [comment]
This has been fixed. https://slack.openmined.org
