### ISSUE TITLE
Example usage of seal api

### ISSUE THREAD

**Issue by siamakz** [OpenMined/TenSEAL#295]
Hello,

I am wondering how to use the tenseal.sealapi. For example, is it possible to do all the steps [here](https://github.com/microsoft/SEAL/blob/main/native/examples/4_ckks_basics.cpp) using the seal api? If yes, I am not sure how to do it. Any help will be appreciated!

**Comment by bcebere** [comment]
Hello @siamakz 

You can find several examples for the sealapi submodule in the tests sections [here](https://github.com/OpenMined/TenSEAL/tree/master/tests/python/sealapi). I hope this helps you.
