### ISSUE TITLE
How to print ts.ckks_vector

### ISSUE THREAD

**Issue by houseshiliang** [OpenMined/TenSEAL#302]
## Question
How to print ts.ckks_vector or save ts.ckks_vector in a file（eg, txt file）?

## Further Information
context = ts.context(
        ts.SCHEME_TYPE.CKKS,
        poly_modulus_degree=8192,
        coeff_mod_bit_sizes=[60, 40, 40, 60]
    )
    context.generate_galois_keys()
    context.global_scale = 2 ** 40

    a0 = [-0.791,0.791]
    a1 = ts.ckks_vector(context, a0)

I want to save the ciphertext value of a0, instead of getting 
print(a1)=<tenseal.tensors.ckksvector.CKKSVector object at 0x000001D76008C160>

**Comment by youben11** [comment]
There is serialization methods for objects in TenSEAL. The serialization transforms an object into a bytes object, then you can save it however you want. Some examples in serialization tests here https://github.com/OpenMined/TenSEAL/blob/master/tests/python/tenseal/tensors/test_serialization.py
