### ISSUE TITLE
Is the slot count still a bottle neck in tenseal?

### ISSUE THREAD

**Issue by lidh15** [OpenMined/TenSEAL#303]
## Question
Is the slot count still a bottle neck in tenseal?

## Further Information
We all know that a ckks cipher with poly modulus degree equal to 8192 can not hold more than 4096 numbers, thus it's difficult to handle with when I got 4097 numbers.

## Screenshots
Okay, I got no screen shots. I just want to know this before I try tenseal on my computer.

## System Information
 - OS: [LINUX]
 - OS Version: [Ubuntu16.04]
 - Language Version: [Python 3.6.8]
 - Package Manager Version: [pip3 20]

## Additional Context
Probably not.

**Comment by lidh15** [comment]
okay, as it's much simpler to use than SEAL, I tried it in the past few minutes and the slot count is still there disabling matmul, is it possible to support matmul of arbitrary size matrix in the future version?

**Comment by youben11** [comment]
the current implementation uses a single ciphertext for matrix multiplication, and extending this to multiple ciphertexts isn't really straightforward, given the limited constraints that we are putting on the input (not necessarily being of size power of two). So the only way currently is to increase your polynomial modulus to have more slots.
