### ISSUE TITLE
How to serialize and then deserialize CKKS_vectors and CKKS_tensors?

### ISSUE THREAD

**Issue by allanhungria** [OpenMined/TenSEAL#307]
## Question
How do I serialize a CKKS_vector?

## Further Information
I'm running into 

TypeError: can't pickle _tenseal_cpp.CKKSVector objects

whether using pickle or dill.  I saw that you fixed this problem back in May 2020, but apparently there's an issue with that fix?

## Screenshots
<img width="1671" alt="pickling_problem" src="https://user-images.githubusercontent.com/2104840/128568552-323dc28e-80b6-4c9d-9a81-df1d8fa522e1.png">

Here's the full tracestack:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-80-29307060419e> in <module>
      1 base_filename = 'encrypted_df.pkl'
      2 with open(base_filename,'wb') as pickle_file:
----> 3     dill.dump(encrypted_df,pickle_file)

~/anaconda3/lib/python3.7/site-packages/dill/_dill.py in dump(obj, file, protocol, byref, fmode, recurse, **kwds)
    274     _kwds = kwds.copy()
    275     _kwds.update(dict(byref=byref, fmode=fmode, recurse=recurse))
--> 276     Pickler(file, protocol, **_kwds).dump(obj)
    277     return
    278 

~/anaconda3/lib/python3.7/site-packages/dill/_dill.py in dump(self, obj)
    496             raise PicklingError(msg)
    497         else:
--> 498             StockPickler.dump(self, obj)
    499         stack.clear()  # clear record of 'recursion-sensitive' pickled objects
    500         return

~/anaconda3/lib/python3.7/pickle.py in dump(self, obj)
    435         if self.proto >= 4:
    436             self.framer.start_framing()
--> 437         self.save(obj)
    438         self.write(STOP)
    439         self.framer.end_framing()

~/anaconda3/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    547 
    548         # Save the reduce() output and finally memoize the object
--> 549         self.save_reduce(obj=obj, *rv)
    550 
    551     def persistent_id(self, obj):

~/anaconda3/lib/python3.7/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    660 
    661         if state is not None:
--> 662             save(state)
    663             write(BUILD)
    664 

~/anaconda3/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

~/anaconda3/lib/python3.7/site-packages/dill/_dill.py in save_module_dict(pickler, obj)
    988             # we only care about session the first pass thru
    989             pickler._session = False
--> 990         StockPickler.save_dict(pickler, obj)
    991         log.info("# D2")
    992     return

~/anaconda3/lib/python3.7/pickle.py in save_dict(self, obj)
    857 
    858         self.memoize(obj)
--> 859         self._batch_setitems(obj.items())
    860 
    861     dispatch[dict] = save_dict

~/anaconda3/lib/python3.7/pickle.py in _batch_setitems(self, items)
    883                 for k, v in tmp:
    884                     save(k)
--> 885                     save(v)
    886                 write(SETITEMS)
    887             elif n:

~/anaconda3/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    547 
    548         # Save the reduce() output and finally memoize the object
--> 549         self.save_reduce(obj=obj, *rv)
    550 
    551     def persistent_id(self, obj):

~/anaconda3/lib/python3.7/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    660 
    661         if state is not None:
--> 662             save(state)
    663             write(BUILD)
    664 

~/anaconda3/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

~/anaconda3/lib/python3.7/pickle.py in save_tuple(self, obj)
    787         write(MARK)
    788         for element in obj:
--> 789             save(element)
    790 
    791         if id(obj) in memo:

~/anaconda3/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

~/anaconda3/lib/python3.7/pickle.py in save_list(self, obj)
    817 
    818         self.memoize(obj)
--> 819         self._batch_appends(obj)
    820 
    821     dispatch[list] = save_list

~/anaconda3/lib/python3.7/pickle.py in _batch_appends(self, items)
    841                 write(MARK)
    842                 for x in tmp:
--> 843                     save(x)
    844                 write(APPENDS)
    845             elif n:

~/anaconda3/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    547 
    548         # Save the reduce() output and finally memoize the object
--> 549         self.save_reduce(obj=obj, *rv)
    550 
    551     def persistent_id(self, obj):

~/anaconda3/lib/python3.7/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    660 
    661         if state is not None:
--> 662             save(state)
    663             write(BUILD)
    664 

~/anaconda3/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

~/anaconda3/lib/python3.7/pickle.py in save_tuple(self, obj)
    787         write(MARK)
    788         for element in obj:
--> 789             save(element)
    790 
    791         if id(obj) in memo:

~/anaconda3/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

~/anaconda3/lib/python3.7/pickle.py in save_list(self, obj)
    817 
    818         self.memoize(obj)
--> 819         self._batch_appends(obj)
    820 
    821     dispatch[list] = save_list

~/anaconda3/lib/python3.7/pickle.py in _batch_appends(self, items)
    841                 write(MARK)
    842                 for x in tmp:
--> 843                     save(x)
    844                 write(APPENDS)
    845             elif n:

~/anaconda3/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    547 
    548         # Save the reduce() output and finally memoize the object
--> 549         self.save_reduce(obj=obj, *rv)
    550 
    551     def persistent_id(self, obj):

~/anaconda3/lib/python3.7/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    660 
    661         if state is not None:
--> 662             save(state)
    663             write(BUILD)
    664 

~/anaconda3/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

~/anaconda3/lib/python3.7/site-packages/dill/_dill.py in save_module_dict(pickler, obj)
    988             # we only care about session the first pass thru
    989             pickler._session = False
--> 990         StockPickler.save_dict(pickler, obj)
    991         log.info("# D2")
    992     return

~/anaconda3/lib/python3.7/pickle.py in save_dict(self, obj)
    857 
    858         self.memoize(obj)
--> 859         self._batch_setitems(obj.items())
    860 
    861     dispatch[dict] = save_dict

~/anaconda3/lib/python3.7/pickle.py in _batch_setitems(self, items)
    888                 k, v = tmp[0]
    889                 save(k)
--> 890                 save(v)
    891                 write(SETITEM)
    892             # else tmp is empty, and we're done

~/anaconda3/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    522             reduce = getattr(obj, "__reduce_ex__", None)
    523             if reduce is not None:
--> 524                 rv = reduce(self.proto)
    525             else:
    526                 reduce = getattr(obj, "__reduce__", None)

TypeError: can't pickle _tenseal_cpp.CKKSVector objects

## System Information
 - OS: macOS Catalina
 - OS Version:  10.15.3
 - Language Version: python 3.7.4
 - Package Manager Version: Conda 4.9.2, but I used pip 21.2.2 to get TenSEAL as it wasn't available through anaconda.

## Additional Context
I've taken my dataframe and encoded column by column, in order to preserve column names through the encryption process, but the same thing happens when I try to serialize a CKKS_tensor.

**Comment by a7853z** [comment]
@allanhungria Having the same issue. Any luck solving this?

**Comment by bcebere** [comment]
@a7853z and @allanhungria 

We explicitly disabled `pickle` support, because it complicates the context management.

We offer serialize/deserialize calls in each object, to achieve that.

You can see (examples in the tests)[https://github.com/OpenMined/TenSEAL/blob/master/tests/python/tenseal/tensors/test_serialization.py].

I hope this helps.

**Comment by a7853z** [comment]
> https://github.com/OpenMined/TenSEAL/blob/master/tests/python/tenseal/tensors/test_serialization.py
@bcebere   Thanks, this helps.

**Comment by allanhungria** [comment]
@bcebere Not to mention pickling would not be secure, which I suppose would violate the whole point of the enterprise.  When I posed the question, I didn't realize the abstract tensor class that ckks_tensor inherits from had serialization/deserialization within it.  My fault for not looking deeply enough into the code.  That's why I closed the issue.
