### ISSUE TITLE
Comparison of encrypted numbers

### ISSUE THREAD

**Issue by ChangYenTing** [OpenMined/TenSEAL#314]
## Question
After the encrypted number is calculated, can it be judged whether it is less than 0?

## Screenshots
![image](https://user-images.githubusercontent.com/45898497/129992624-88022f5c-bf0c-4910-8a61-79ad3181a7f6.png)

![image](https://user-images.githubusercontent.com/45898497/129992813-c3940757-ed37-4d29-b1c6-73fe4e5b3301.png)

**Comment by youben11** [comment]
I fear not, otherwise, you would be able to know the encrypted value by comparing the encrypted value to some set of plain values
