### ISSUE TITLE
how to explain accuracy under the encrypted data is a little higher than that of the plain data

### ISSUE THREAD

**Issue by napoay** [OpenMined/TenSEAL#315]
## Question

How to explain this phenomenon, the accuracy under the encrypted data is a little higher than that of the plain data?

## Further Information

![22](https://user-images.githubusercontent.com/38783332/130320671-1cdb034c-5fcb-40a6-9992-0faceb389727.PNG)

I guess it is caused by the noise of the CKKS scheme.

**Comment by youben11** [comment]
What I would expect is that some evaluation present a 51/49 percent probabilities for the different classes, making those examples really sensitive to noise. Examples like that could be classified the other way, with maybe 49/51 percent probabilities. This is just a guess, but I don't remember doing an investigation of the cause
