### ISSUE TITLE
How to Run Enc() over GPU?

### ISSUE THREAD

**Issue by SaintJackson** [OpenMined/TenSEAL#316]
Hi,

I am wondering if cuda computation is available in Enc() function from Tutorial 4 MNIST Dataset. 

How to convert data to cuda tensors while doing encryption? Is it possible?

**Comment by RobertLucian** [comment]
Curious about this too!

**Comment by youben11** [comment]
TenSEAL does not provide ways to compute on GPU

**Comment by SaintJackson** [comment]
Thanks. Looking forward to GPU feature if possible : )
