### ISSUE TITLE
Relinearization [and Rescaling]

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#35]
After every multiplication for CKKS and BFV, we need to relinearize our ciphertext, CKKS also need rescaling (as the scale becomes Delta**2). We need to have these operations done automatically by default after every multiplication, with the ability to choose to not do so.

**Comment by RafiulIslamRafi** [comment]
Which function gives Relinearization in TenSEAL? when I multiply a variable for 2nd time in cyphertext, it returns a garbage result.
