### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by dimk1** [OpenMined/TenSEAL#357]
## Description
I am unable to run some basic functionality. I have SEAL installed and tenSEAL installed via the pip installation command. I then run:

```
$ python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tenseal as ts
>>> context = ts.context(ts.SCHEME_TYPE.BFV, poly_modulus_degree=4096, plain_modulus=1032193)
Illegal instruction (core dumped)
```

and the program is aborted.

**Comment by bcebere** [comment]
Hello @dimk1 

Testing your snippet using TenSEAL 3.5 on Ubuntu seems to work fine.

Could you please provide more details about your setup? TenSEAL version and the OS.

Thanks!

**Comment by CAPTAIN320** [comment]
I switched from version 0.3.6 to 0.3.4 and it started working.
