### ISSUE TITLE
Should we disable SEAL_THROW_ON_TRANSPARENT_CIPHERTEXT?

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#36]
Default build of SEAL enforce SEAL_THROW_ON_TRANSPARENT_CIPHERTEXT to on which will throw an error whenever the result ciphertext of an evaluation is transparent.

Current implementation workaround issues regarding transparent ciphertexts in vector operations #33. An open question is whether we should disable it completely? Does our use cases get affected?

**Comment by bcebere** [comment]
Wouldn't be a better solution to:
 - add a try/catch block when multiplying with a plaintext.
 - in case of a logic_error, just replace the ciphertext with the output from encrypt_zero.
?

just wondering.
Maybe they enforce it for a good reason.

**Comment by youben11** [comment]
They mainly enforce it because the output ciphertext is clearly encrypting 0, you won't need the secret key to know that. @LaRiffle recently suggested that we disable this completely as it will be equivalent for doing MPC with additive sharing and multiplying shares with zero. Here both the party doing the computation and the secret key holder can know that the result is an encrypted zero, the threat is that for transparent ciphertext others can know that as well.

We may need to think more about alternatives, the best I guess would be to let the user decide what to do with this error, but we also wants to keep it simple for him.

**Comment by bcebere** [comment]
I can work on this, if it's not already assigned.

I will disable  SEAL_THROW_ON_TRANSPARENT_CIPHERTEXT from cmake opts.

**Comment by youben11** [comment]
Still not sure what's the best way to go ...

**Comment by youben11** [comment]
> Wouldn't be a better solution to:
> 
>  * add a try/catch block when multiplying with a plaintext.
> 
>  * in case of a logic_error, just replace the ciphertext with the output from encrypt_zero.
>       ?

I think we will go with this one, and we should replace with encrypt_zero when appropriate, any final thoughts on this @bcebere ?

ping @philomath213

**Comment by bcebere** [comment]
Sounds good to me!

**Comment by philomath213** [comment]
Yeah, I think this the most convenient solution.
