### ISSUE TITLE
Illegal instruction (core dumped) with tenseal-0.3.6

### ISSUE THREAD

**Issue by rogerppp** [OpenMined/TenSEAL#363]
## Description
Illegal instruction (core dumped) 

I used "pip install tenseal" to install tenseal-0.3.6
then I tried to set the context

> import tenseal as ts
> context = ts.context(
           ts.SCHEME_TYPE.CKKS,
          poly_modulus_degree=8192,
           coeff_mod_bit_sizes=[60, 40, 40, 60]
         )

>Illegal instruction (core dumped)

But, when I changed the  version of tenseal to 0.3.5, it's working.
OS: ubuntu 20.04
python: 3.9.7

**Comment by bcebere** [comment]
Hello,

Before every release, we have [automated tests](https://github.com/OpenMined/TenSEAL/actions) covering the matrix {Windows Server 2019, OSX 10.15, Ubuntu 20.04} x Python { 3.7, 3.8, 3.9}.
The tests pass. We wouldn't publish a version that constantly crashes.

It would help to understand your setup: what versions of gcc/clang do you have installed?
Can you upload the stacktrace generated in the coredump? 

Thank you!

**Comment by bcebere** [comment]
Hello,

Thank you for your patience. 

After some investigation, it turns out the HEXL library was crashing on some configurations, including Colab envs.

The latest release, TenSEAL 0.3.8, should fix the issue.

Please let us know if you are still encountering the problem.
