### ISSUE TITLE
Google Colab crash (tutorial 0)

### ISSUE THREAD

**Issue by iciac** [OpenMined/TenSEAL#365]
Running tutorial 0 on Google Colab (Python 3.7.12) causes the session kernel to crash. Tested using tenseal 0.3.5 and 0.3.6 on CPU and GPU instances. 

Installation: 'pip install tenseal' 
Import: 'import tenseal as ts' 
Crash: 'context = ts.context(ts.SCHEME_TYPE.BFV, poly_modulus_degree=4096, plain_modulus=1032193)'

Creating the context causes the kernel to restart (the logs are listed below). 
<img width="513" alt="Screen Shot 2021-12-06 at 12 56 39 pm" src="https://user-images.githubusercontent.com/47710784/144777365-4aabc127-0106-4615-9776-2fda80e2069f.png">

**Comment by bcebere** [comment]
Hello,

Thank you for your patience. 

After some investigation, it turns out the HEXL library was crashing on some configurations, including Colab envs.

The latest release, TenSEAL 0.3.8, should fix the issue.

Please let us know if you are still encountering the problem.
