### ISSUE TITLE
ValueError: can't execute conv2d_im2col on chunked vectors

### ISSUE THREAD

**Issue by Ti-Oluwanimi** [OpenMined/TenSEAL#376]
## Question
Why does this happen during the inference stage?

ValueError                                Traceback (most recent call last)
<ipython-input-9-b3bf74d70f56> in <module>
      1 enc_model = enc_cnn(model)
----> 2 enc_test(context, enc_model, test_loader, criterion, kernel_shape, stride)

<ipython-input-5-b186be09c784> in enc_test(context, model, test_loader, criterion, kernel_shape, stride)
     13         # targets = targets.to(device=device)
     14         ## Forward Pass
---> 15         scores = enc_model(x_enc, windows_nb)
     16         output = scores.decrypt()
     17         output = torch.tensor(output).view(1,-1)

<ipython-input-4-1fb4f8d48b31> in __call__(self, *args, **kwargs)
     35 
     36     def __call__(self, *args, **kwargs):
---> 37         return self.forward(*args, **kwargs)

<ipython-input-4-1fb4f8d48b31> in forward(self, enc_x, windows_nb)
     20         enc_channels = []
     21         for kernel, bias in zip(self.conv1_weight, self.conv1_bias):
---> 22             y = enc_x.conv2d_im2col(kernel, windows_nb) + bias
     23             enc_channels.append(y)
     24         # pack all channels into a single flattened vector

~/anaconda3/lib/python3.8/site-packages/tenseal/tensors/ckksvector.py in conv2d_im2col(self, other, windows_nb)
    181     def conv2d_im2col(self, other, windows_nb) -> "CKKSVector":
    182         other = self._conv2d_im2col(other)
--> 183         return self._wrap(self.data.conv2d_im2col(other, windows_nb))
    184 
    185     def conv2d_im2col_(self, other, windows_nb) -> "CKKSVector":

ValueError: can't execute conv2d_im2col on chunked vectors

## Further Information
on a one layer network, at the encryption stage

## System Information
 - Ubuntu
 - 18
 - Language Version: [e.g. Python 3.8.8

**Comment by poilog** [comment]
How did you solve the problem？

**Comment by poilog** [comment]
@Ti-Oluwanimi

**Comment by Ti-Oluwanimi** [comment]
No. It seems TenSEAL's limit is the number of convolution layers it can encrypt. I finally resorted to using hybridized MPC like Delphi and Cheetah protocols to test my algorithm

**Comment by poilog** [comment]
OK. Thank you for your reply.

**Comment by elina-israyelyan** [comment]
I am getting the same error when trying to conv2d on one channel of the image. I have 64x64x3 image and I only take one channel with size 64x64 and trying to encrypt and use conv2d_im2col but It still doesn't work
