### ISSUE TITLE
Property `shape` missing for `CKKSVector`

### ISSUE THREAD

**Issue by mrader1248** [OpenMined/TenSEAL#379]
## Description
The property `shape` is missing for `CKKSVector`.

## How to Reproduce
Use the following piece of code to reproduce the bug.
```python
import numpy as np
import tenseal as ts

context = ts.context(
    ts.SCHEME_TYPE.CKKS,
    poly_modulus_degree=8192,
    coeff_mod_bit_sizes=[60, 40, 40, 60]
)
context.global_scale = 2**40

a = ts.ckks_tensor(context, np.arange(16.0))
print(a.shape)

a = ts.ckks_vector(context, np.arange(16.0))
print(a.shape)
```

## Expected Behavior
The two print statements in the code above are expected to both print `"[16]"`. While the first print statement executes as expected, the second one (specifically calling the property `shape`) fails with
```
AttributeError: '_tenseal_cpp.CKKSVector' object has no attribute 'shape'
```

## System Information
 - OS: Manjaro via WSL 2
 - OS Version: N/A
 - Language Version: Python 3.9.7
 - Package Manager Version: pip 21.2.4

**Comment by youben11** [comment]
Thanks for the issue @mrader1248 but this is not a bug, but a feature request. Vector types do have a `size `attribute but not a `shape`

**Comment by mrader1248** [comment]
Forgive me, but I disagree with you on that. The class `CKKSVector` is derived from `AbstractTensor`, which defines the property `shape`. Therefore, from an OOP-POV, the child class `CKKSVector` has to support this property.
