### ISSUE TITLE
Holds the scale in TenSEALContext

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#38]
This issue is mainly related to the use of the CKKS scheme

### Motivation

1. API would be simpler if the user provides the `scale` once at context creation, this wasn't the case because we thought that the user would need to choose the scale for each tensor.
1. In a secure computation which is controlled by a single TenSEALContext, we will generally wants to have the same scale for all our ciphertexts.
1. After some multiplication and rescaling operations, we will sometimes need to assume that all ciphertexts are on the same scale, while this is not true, the ratio between the actual scales should be around 1 if the initial scales used for encoding were the same.

### Proposed solution

Hold the scale in the TenSEALContext for CKKS: this can also help us advise the user of choosing coeff modulus that are ~= sclae (e.g. scale=2**20 & coeff_mod_bit_sizes=[X, 20, 20, X]). Every multiplication should rescale the ciphertext using the next coeff modulus. If we assume that the initial scale is a power of two and that the coeff_modulus are of the same bit size as the initial scale, then all ciphertext should have a scale ~= init_scale no matter their multiplicative depth.

Ping: @philomath213 @s0l0ist

**Comment by s0l0ist** [comment]
This is a good start to the right idea, but I also feel it would add an effort so ensure this doesn’t break in future versions of SEAL implementation or even this library. 

I would propose a separate helper tool to help define the appropriate encryption parameters and scale based off of the desired algorithmic depth.  This could be thought of as the equivalent to the`CoeffModulus::BFVDefault` function used to generate the coeff moduli for the BFV scheme. 

This tool should not be coupled strongly to the native SEAL API nor this library any way, therefore posing no risk to either.

**Comment by philomath213** [comment]
Good idea to simplify the API.
But since the scale is related to CKKS tensor, why don't we make it a CKKS tensor attribute, and generate or set it during tensor creation?

**Comment by youben11** [comment]
> This is a good start to the right idea, but I also feel it would add an effort to ensure this doesn’t break in future versions of SEAL implementation or even this library.
> 
> I would propose a separate helper tool to help define the appropriate encryption parameters and scale based off of the desired algorithmic depth. This could be thought of as the equivalent to the`CoeffModulus::BFVDefault` function used to generate the coeff moduli for the BFV scheme.
> 
> This tool should not be coupled strongly to the native SEAL API nor this library any way, therefore posing no risk to either.

In TenSEAL, we assume that the user doesn't have enough experience in HE to deal with relin and rescaling, it would certainly be difficult on our side to deal with all these details while assuming general usage, but I think motivation(2) is a good assumption that simplify this solution. And of course we will need to give experienced user the ability to use different scale, for instance, users can still create CKKSVector with a different scale, but if they don't provide then we just use our context's scale. They should also be able to disable all these operations done after every multiplication if they want to deal with rescaling differently, but a rescaling strategy is really important for TenSEAL to be really simple to use.

**Comment by youben11** [comment]
> Good idea to simplify the API.
> But since the scale is related to CKKS tensor, why don't we make it a CKKS tensor attribute, and generate or set it during tensor creation?

Mainly because of motivation(2), we don't need to set the scale for every tensor, all tensors should be having the same scale. The scale isn't a big field, using it in the TenSEALContext for CKKS and wasting that space for BFV isn't a big deal.

**Comment by s0l0ist** [comment]
> In TenSEAL, we assume that the user doesn't have enough experience in HE to deal with relin and rescaling, it would certainly be difficult on our side to deal with all these details while assuming general usage, but I think motivation(2) is a good assumption that simplify this solution. And of course we will need to give experienced user the ability to use different scale, for instance, users can still create CKKSVector with a different scale, but if they don't provide then we just use our context's scale. They should also be able to disable all these operations done after every multiplication if they want to deal with rescaling differently, but a rescaling strategy is really important for TenSEAL to be really simple to use.

Okay, if you're already building a lot of helper logic then this makes sense to encapsulate as long as it is overridable.
