### ISSUE TITLE
Cannot install on Windows 11

### ISSUE THREAD

**Issue by austincarthy** [OpenMined/TenSEAL#383]
## Description
"pip install tenseal" produces an error and does not install

Error message:
"ERROR: Could not find a version that satisfies the requirement tenseal (from versions: none)
ERROR: No matching distribution found for tenseal"

## How to Reproduce
<img width="510" alt="tenseal_install_error" src="https://user-images.githubusercontent.com/47009443/159773258-5e602c3a-ecff-4dd3-a46d-e479eae4631b.png">

## System Information
 - OS: Windows 11 Home
 - OS Version: 22000.556
 - Language Version: Python 3.10.3, pip 22.0.4

**Comment by bcebere** [comment]
Hello,

The problem is that there is no Python 3.10 release on PyPI.
I triggered a release for py3.10, it should be up in ~1h, after the tests pass.

Let me know if it still fails for you then.

**Comment by austincarthy** [comment]
Thank you, it works!
