### ISSUE TITLE
How can i print data of a Ciphertext using Tenseal ?

### ISSUE THREAD

**Issue by Fishermanljh** [OpenMined/TenSEAL#396]
## Question
**Describe your question in ONE SENTENCE.**

## Further Information
Describe your question in greater length here.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by Henrikls** [comment]
Hi Fishermanljh 

You can print the encrypted vector just using a normal print call.

If you want to print the unencrypted vector then you should do something along the lines of: 
print(enc_v1.decrypt())

An example where you can print both is given in both the readme and below:

import tenseal as ts

# Setup TenSEAL context
context = ts.context(
            ts.SCHEME_TYPE.CKKS,
            poly_modulus_degree=8192,
            coeff_mod_bit_sizes=[60, 40, 40, 60]
          )
context.generate_galois_keys()
context.global_scale = 2**40

v1 = [0, 1, 2, 3, 4]

# encrypted vectors
enc_v1 = ts.ckks_vector(context, v1)
#printing an encrypted vector should show you the placement of the vector
print(enc_v1)
#while printing a decrypted vector should show you the values of v1 with a minor error e
print(enc_v1.decrypt())

**Comment by Fishermanljh** [comment]
Hi Henriks, many thanks for your reply.  

I called the print function, which came out to be:
**<tenseal.tensors.ckksvector.CKKSVector object at 0x0000029D316DB5B0>**

To be specific,  if I encrypted the raw data: [1], could I know its Ciphertext just in a single large value, like 2*10^100, instead of the CKKSVector object?

**Comment by Henrikls** [comment]
Seal shows you the location of the encrypted object. My assumption is that when the object gets encrypted it will most likely look like gibberish where for example the vector: [1] ends up being scrambled into something along the lines of:

gfswuCsl7X2HiW2bDKuBUDWu9ja0ZkV7Vc6LqIwifJ7dUpr/9YbvdLpWIQcsP5mQYsoVIDYwRunEVfeHGmhUOKTGQmk7BpZ6pdiZdbyJLKQnHsWypWoJijoc7F/MhHP6FBjNJwtNWHQxtOK5XIM5/gR9tPo2K89h7zM1lLsHfCThwxM6VCmw1S3P2IpG5cpo8nedOdWfWP3KKAyd8O1sofnQl5S/GV0KHWxrIK6FWpqeDagOfkubehPZ20OH1MwyU+DhZslBU/D5wVJwgcVCS438++0wNbKRfPQQO3yW1atXDoOeVe2weS5BlzgLbES/0zrJCFtEEHKXogoR5XXrLQ==

(This was made using RSA which also is said to have homomorphic properties)

Therefore to answer your question you could not know the ciphertext in a single large value but rather as a string of gibberish.
If you want to save the encrypted object so you can have a look at it then I would recommend using the original SEAL library which Tenseal is built upon and then follow along with what Kim Laine is suggesting in the following issue: 
https://github.com/microsoft/SEAL/issues/6 

I also saw that you have been looking at Lattigo, if you are interested in trying out seal for python then I would personally recommend you to also look at https://github.com/Huelse/SEAL-Python 
Which should provide you with some more functions so you can get a bit more technical when programming.

I hope I was able to help :)

**Comment by Fishermanljh** [comment]
Hi Henriks,


Many thanks for your time, and it has been very helpful.


I got your point, and it seems unable to get a large single value of an Ciphertext encrypted by the CKKS method.



The reason why I raised out such question is that when I was reading some research papers, which reads that the Ciphertext encrypted by the Pillar method coded in C could support such function.


Your reply well addressed my concerns, and thanks again.



Best regards,
Johnny





------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "OpenMined/TenSEAL"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, May 13, 2022 03:14 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [OpenMined/TenSEAL] How can i print data of a Ciphertext using Tenseal ? (Issue #396)





 
Seal shows you the location of the encrypted object. My assumption is that when the object gets encrypted it will most likely look like gibberish where for example the vector: [1] ends up being scrambled into something along the lines of:
 
gfswuCsl7X2HiW2bDKuBUDWu9ja0ZkV7Vc6LqIwifJ7dUpr/9YbvdLpWIQcsP5mQYsoVIDYwRunEVfeHGmhUOKTGQmk7BpZ6pdiZdbyJLKQnHsWypWoJijoc7F/MhHP6FBjNJwtNWHQxtOK5XIM5/gR9tPo2K89h7zM1lLsHfCThwxM6VCmw1S3P2IpG5cpo8nedOdWfWP3KKAyd8O1sofnQl5S/GV0KHWxrIK6FWpqeDagOfkubehPZ20OH1MwyU+DhZslBU/D5wVJwgcVCS438++0wNbKRfPQQO3yW1atXDoOeVe2weS5BlzgLbES/0zrJCFtEEHKXogoR5XXrLQ==
 
(This was made using RSA which also is said to have homomorphic properties)
 
Therefore to answer your question you could not know the ciphertext in a single large value but rather as a string of gibberish.
 If you want to save the encrypted object so you can have a look at it then I would recommend using the original SEAL library which Tenseal is built upon and then follow along with what Kim Laine is suggesting in the following issue:
 microsoft/SEAL#6
 
I also saw that you have been looking at Lattigo, if you are interested in trying out seal for python then I would personally recommend you to also look at https://github.com/Huelse/SEAL-Python
 Which should provide you with some more functions so you can get a bit more technical when programming.
 
I hope I was able to help :)

**Comment by Henrikls** [comment]
Glad I could help I got a bit unsure if what I was writing was useful or correct (hence why it got deleted) so I had to double check with one of my pals. I'll leave the last draft of my explanation for future onlookers.

TenSeal shows you the location of the encrypted object. My assumption is that when the object gets encrypted it will most likely look like gibberish where for example the vector: [1] ends up being scrambled into something along the lines of:

gfswuCsl7X2HiW2bDKuBUDWu9ja0ZkV7Vc6LqIwifJ7dUpr/9YbvdLpWIQcsP5mQYsoVIDYwRunEVfeHGmhUOKTGQmk7BpZ6pdiZdbyJLKQnHsWypWoJijoc7F/MhHP6FBjNJwtNWHQxtOK5XIM5/gR9tPo2K89h7zM1lLsHfCThwxM6VCmw1S3P2IpG5cpo8nedOdWfWP3KKAyd8O1sofnQl5S/GV0KHWxrIK6FWpqeDagOfkubehPZ20OH1MwyU+DhZslBU/D5wVJwgcVCS438++0wNbKRfPQQO3yW1atXDoOeVe2weS5BlzgLbES/0zrJCFtEEHKXogoR5XXrLQ==

(This was made using RSA which also is said to have homomorphic properties)

Therefore to answer your question you could not know the ciphertext in a single large value but rather as a string of gibberish.
If you want to save the encrypted object so you can have a look at it then I would recommend using the original SEAL library which Tenseal is built upon and then follow along with what Kim Laine is suggesting in the following issue: 
https://github.com/microsoft/SEAL/issues/6
