### ISSUE TITLE
How can it be that I get scale out of bounds when multiplying?

### ISSUE THREAD

**Issue by Henrikls** [OpenMined/TenSEAL#397]
I am getting the error "scale out of bounds" when I am trying to make a multiplication of two encrypted vectors how can I fix this?

I am working on a project where I want to see if it would be possible for me to make a homomorphic eigenface recognition, and I've stumbled on the problem that after some time then I am no longer capable of multiplying my vectors. 

Firstly then I am using CKKS where I am handling the elements of the pictures as if they themselves are CKKSvectors meaning that given a vector containing values as such:

[1,2,3,4]

Then the corresponding encrypted vector is:
[CKKSVector, CKKSVector, CKKSVector, CKKSVector]

The reason for why it is encrypted this way is so that I can use my version of PCA on the pictures. However when I try and run my PCA method then I am unable to multiply the encrypted CKKSVectors when forming the covariance matrix. I normally don't have any problems with multiplying or np.dot for that matter but in this case something goes completely wrong. 

To be more exact then this is the error I get when using np.dot:
![image](https://user-images.githubusercontent.com/60431169/167482705-bd5d9a65-7785-4ba8-beef-f8535e7a14d4.png)
![image](https://user-images.githubusercontent.com/60431169/167482913-7b91ebd5-d80f-4cca-b0a8-5389e7e7048f.png)

I also tried implementing the matrix multiplication myself to see if that would help but alas nothing works.
(And I know I should append to be able to get anything useful out of the calculations but I will burn that bridge later.)
The matrix multiplication function looks like this:
def matrix_mult(m1,m2):
    r1 = len(m1)         #mxn 
    r2 = len(m2)      #nxk
    c2 = len(m2[0])
    mul2 = np.zeros((r1,c2))
    for i in range(0,r1):
        for j in range(0,c2):
            for k in range(0,r2):
                mul2[i][j] = mul2[i][j] + m1[i][k]*m2[k][j]
    return mul2

As soon as I come to any multiplication in matrix_mult then the error "scale out of bounds" shows up:
![image](https://user-images.githubusercontent.com/60431169/167483382-10eff75a-6a25-4811-b178-3d3221b81f6b.png)

I am using an ubuntu VM which is running python version 3.8.10 and tenseal version: 0.3.10.

**Comment by MartinNoc** [comment]
Hello @Henrikls 
would you be so kind and give some details of your code, espacially where you generate your context.

As an example: With the following context you are able to perform **three** multiplications before a "scale out of bounds" error would occur. This is because of the five coeff_mod_bit_sizes. Detailed example see [here](https://github.com/microsoft/SEAL/blob/main/native/examples/3_levels.cpp#L51).
```
# Create TenSEAL context
bits_scale = 32
context = ts.context(
    ts.SCHEME_TYPE.CKKS,
    poly_modulus_degree=8192,
    coeff_mod_bit_sizes=[50,40,40,40,50]
)
context.global_scale = 2**bits_scale
context.generate_galois_keys()
```

Best,
Martin

**Comment by Henrikls** [comment]
my context is made the following way: 
context = ts.context(
            ts.SCHEME_TYPE.CKKS,
            poly_modulus_degree=32768,
            coeff_mod_bit_sizes=[60, 40, 40, 60]
          )

context.global_scale = 2**40
context.generate_galois_keys()

Thank you Martin
From your comment then I found out that I was only working on level 3 whilst I could be working on level 4 I have now added a 60 to the end of coeff_mod_bit_sizes and are now capable of performing 1 matrix multiplication before meeting the error.
I also found out that reencrypting resets the exhausted level and therefore I have adjusted the matrix_mult formula so that it should reencrypt before return.
my spaghetti code for matrix_mult is shown below:

def matrix_mult(m1,m2):
    r1 = len(m1)         #mxn 
    r2 = len(m2)      #nxk
    c2 = len(m2[0])
    mul2 = []
    mul3 = []
    for i in range(0,r1):
        m_mult = []
        for j in range(0,c2):
            m_mult2 = []
            for k in range(0,r2):
                m_mult2.append(m1[i][k]*m2[k][j])
            m_mult.append(np.sum(m_mult2))
        mul2.append(m_mult)
    mul3.append(reencrypt_pics(mul2))
    return mul3

Thanks once again Martin I have a minor question about ways of encrypting using CKKSVectors.
Is there a way where you can encrypt a whole vector such as:
[1,2,3,4]
Where the corresponding encrypted vector is just one CKKSVector where you can pull each element from it?
I have been trying to make this happen for a while but the only thing I am able to get once I try to pull out the first element is error CKKSVector is not subscribtable. Would the only otherway be to use a vector of same size to extract each element individually such as this [1,0,0,0]?

Kind regards Henrik

**Comment by Henrikls** [comment]
Thank you again you have been a great help :)
