### ISSUE TITLE
No wheel for Linux python 3.10

### ISSUE THREAD

**Issue by MikeWalrus** [OpenMined/TenSEAL#416]
PyPI only has `tenseal-0.3.12-cp310-cp310-win_amd64.whl` and `tenseal-0.3.12-cp310-cp310-macosx_11_0_x86_64.whl` as of now. Can someone upload a package for python 3.10 on Linux please?

**Comment by bcebere** [comment]
Thank you for reporting this. There was a typo in the release script, the package should be available for 3.10 now.
