### ISSUE TITLE
Division of encrypted objects

### ISSUE THREAD

**Issue by srinu1093** [OpenMined/TenSEAL#423]
I'm able to perform addition, subtraction and multiplication on encrypted objects. But while doing the division, I'm getting the error. How can I divide 2 encrypted objects?

**Comment by data-science-lover** [comment]
I think you can't but you can encrypt the inverse of the vector and then do a simple multiplication... It will come back to the same thing and it works as the multiplication is handled on the encrypted objects :

# Setup TenSEAL context
    context = ts.context(
        ts.SCHEME_TYPE.CKKS,
        poly_modulus_degree=8192,
        coeff_mod_bit_sizes=[60, 40, 40, 60]
    )
    context.generate_galois_keys()
    context.global_scale = 2 ** 40

    v1 = np.array([0, 1, 2, 3, 4])
    v2 = np.array([4, 3, 2, 1, 1])

    # encrypted vectors
    enc_v1 = ts.ckks_vector(context, v1)
    enc_v2 = ts.ckks_vector(context, 1/v2)

    result = enc_v1 * enc_v2
    print(result.decrypt())
