### ISSUE TITLE
Make encoders part of TenSEALContext

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#43]
### Context

Current implementation instantiate an encoder whenever needed which might incur some extra overhead, and reserving space for all the 3 different kind of encoders is non-efficient.

### Possible solution

Keep 3 pointers to all kind of encoders in `TenSEALContext` (`[Integer|Batch]Encoder` for BFV and `CKKSEncoder` for CKKS) and have a method `get_encoder` that when asked for a specific encoder, check either it's created or not yet, create a new one if it's not, and return a pointer to the encoder.

**Question to take into account:** is it safe to share pointers to encoders? are they thread-safe?

**Comment by bcebere** [comment]
I can work on this, if it's not already assigned.
