### ISSUE TITLE
Tests to verify the size of the ciphertext after the ct-ct multiplication

### ISSUE THREAD

**Issue by philomath213** [OpenMined/TenSEAL#44]
As @bcebere mentioned in #42, it would be nice to add some tests that verify the size of the ciphertext after the ct-ct multiplication.

###  Issue
Since Ciphertext is a private attribute for CKKS and BFV vectors and there's no python binding for that, we can't use python test in this case.

**Comment by bcebere** [comment]
imo, some approaches can be:

1. Add a separated library to the CMake, with extra bindings, that exposes more information and it is used only for the tests. It doesn't get published. One extra information is exposing ciphertext data. The downside is that you don't get to test the actual delivered binary.

2. Add a new parameter to the TensealContext, denoting a settings json/yaml, for pushing customizations to the context. One option can be how often to relinearize or how verbose to log. 
One interesting option here could be adding an IPC path(TCP or Linux path), where the library will write different events/information, and the tester/anyone interested can listen and assert the output. This kind of hooks would pe pretty useful for deeper testing, I think. In particular for asserting expections on the ciphertexts. In case the IPC path is missing, the library won't publish any messages.

**Comment by bcebere** [comment]
Or we could add gmock and gtest as dependecies and test the C++ part directly.

I can work on that.
