### ISSUE TITLE
Not getting installed using pip install tenseal

### ISSUE THREAD

**Issue by akasho805** [OpenMined/TenSEAL#463]
## Description
When trying to install tenseal using : pip install tenseal it is showing no matching distribution found for tenseal

## Expected Behavior
Successfully install tenseal

## Screenshots
![image](https://github.com/OpenMined/TenSEAL/assets/96943885/c13a601d-4015-45e1-8662-61984de35f94)

## System Information
 - OS: [Windows 11]
 - OS Version: [23H2]
 - Python 3.11.4
 - Package Manager Version: [pip 23.3.1]

**Comment by philomath213** [comment]
You should be able to install TenSEAL using pip now.
We just published a new release that supports Python 3.11 and Python 3.12.
