### ISSUE TITLE
Failed to install tenseal, windows

### ISSUE THREAD

**Issue by svetlana-boudko** [OpenMined/TenSEAL#470]
Runing: pip install tenseal fails with the following:
ERROR: Could not find a version that satisfies the requirement tenseal (from versions: none)
ERROR: No matching distribution found for tenseal

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS: Windows 11 Enterprise
 - Language Version: Python 3.12.0
 - pip 24.0

**Comment by svetlana-boudko** [comment]
using:

git clone --recursive https://github.com/OpenMined/TenSEAL.git
cd TenSEAL/
git submodule init
git submodule update
pip install .

didn't help either.

**Comment by ryunnnn** [comment]
> 用：
> 
> git clone --recursive https://github.com/OpenMined/TenSEAL.git cd TenSEAL/ git submodule init git submodule update pip install .
> 
> 也无济于事。

python版本高了不兼容应该是，我3.8的能下

**Comment by philomath213** [comment]
You should be able to install TenSEAL using pip now.
We just published a new release that supports Python 3.11 and Python 3.12.
