### ISSUE TITLE
Can't install TenSEAL on Windows

### ISSUE THREAD

**Issue by martinsandor707** [OpenMined/TenSEAL#475]
## Description
Can't install TenSEAL on Windows

## How to Reproduce
1. `pip install tenseal`

## Expected Behavior
TenSEAL should be installed.

## System Information
 - OS: Windows
 - OS Version: 10
 - Language Version: Python 3.11.9
 - Package Manager Version: Pip 24.0

## Additional Context
Regular `pip install tenseal` simply doesn't find a tenseal version on pypi. I tried installing from a cloned repository, but I got the following error message instead:
`
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tenseal
Failed to build tenseal
ERROR: Could not build wheels for tenseal, which is required to install pyproject.toml-based projects
`

I have gcc, cmake and protocol buffers all installed and working fine. I tried to build TenSEAL manually, and cmake ran without problems, but but `cmake --build` errored out, throwing thousands of errors along the line of:

`
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\atomic(106,9): error C2039: '
_invalid_parameter': is not a member of '`global namespace'' [C:\TenSEAL\build\_tenseal_cpp.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\i
`

I am completely out of ideas as to how to solve this, but the problem is probably related to [this previous issue](https://github.com/OpenMined/TenSEAL/issues/234).

**Comment by philomath213** [comment]
You should be able to install TenSEAL using pip. We just published a new release that supports Pytjon 3.11 and Python 3.12
