### ISSUE TITLE
Unable to install TenSEAL on Python 3.12.6

### ISSUE THREAD

**Issue by vanvu322** [OpenMined/TenSEAL#494]
I'm trying to install TenSEAL on Python 3.12.6 using the command pip install tenseal, but I'm encountering the following error:
pip install tenseal

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tenseal (from versions: none)
ERROR: No matching distribution found for tenseal

I would appreciate any guidance on how to resolve this problem.
System Info:
Python version: 3.12.6
OS:  Windows 10 64-bit
Pip version: pip 24.2
Thank you in advance!

**Comment by philomath213** [comment]
@vanvu322 Can you please try again.
We just published a new release for the Windows package that supports recent Python versions.

**Comment by vanvu322** [comment]
> @vanvu322 Can you please try again. We just published a new release for the Windows package that supports recent Python versions.

Thank you very much! I tried installing again after the new release was published, and the issue has been successfully resolved. TenSEAL is now installed on my system.
