### ISSUE TITLE
Provide a SEAL API binding to set scale manually after a multiplication

### ISSUE THREAD

**Issue by dhuynh95** [OpenMined/TenSEAL#58]
# Context

Currently after a multiplication has been done, there is no way to set the scale manually to allow further computation such as addition with a plaintext. 

Example : 
```python
# First do a multiplication and rescale
evaluator.multiply(ctx, ptx, output)
evaluator.rescale_to_next_inplace(output)
evaluator.mod_switch_to_inplace(ptx, output.parms_id())

# This is not allowed currently
output.scale(scale)

# Therefore this will fail because seal won't allow two objects of different scale to be summed
evaluator.add_plaintext_inplace(output, ptx)
```

# Proposed solution

I think a simple binding such as ctx.scale(scale) or ctx.set_scale(scale) would be enough to solve this problem.

**Comment by bcebere** [comment]
Fixed with https://github.com/OpenMined/TenSEAL/pull/59

Added a `scale` property to Plaintext/Ciphertext classes, now you can do something like

`output.scale = ptx.scale`
