### ISSUE TITLE
Calling matmul on a medium sized matrix throws an std::bad_alloc exception

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#68]
**Describe the bug**
CKKSVector::matmul_plain seems to be consuming memory linear in the size of the input, a small input matrix works fine, but as we use larger matrices, matmul throw an std::bad_alloc exception.

**To Reproduce**
Script to reproduce: you can increase the size if the exception isn't thrown

```python
import tenseal as ts
import torch

context = ts.context(ts.SCHEME_TYPE.CKKS, 8192, coeff_mod_bit_sizes=[40, 20, 20, 40])
context.global_scale = 2 ** 20
context.generate_galois_keys()

size = 20
mat = torch.rand(size,256).tolist()
vec = ts.ckks_vector(context, [1]*(size))
vec.mm(mat)
```

**Expected behavior**
The operation should return the result of the vector-matrix multiplication.

**Environement (please complete the following information):**
 - OS: Linux
 - TenSEAL Version 0.1.1a0

**Comment by zhangbo2008** [comment]
?how tosolve?

**Comment by youben11** [comment]
Thanks @zhangbo2008, It was fixed in the linked PR
