### ISSUE TITLE
Serialise, deserialise; for pickle, deepcopy

### ISSUE THREAD

**Issue by DreamingRaven** [OpenMined/TenSEAL#72]
## Feature Description
I feel it would be vital to be able to deep-copy objects like context, private key, and ciphertext.
Similarly It will also be vital to real use to be able to pickle, and unpickle, context, private key, and ciphertext, or at the least save to a file-like object, but not necessarily a file itself.

## Is your feature request related to a problem?
I would like to save directly to a non local system such as a database the necessary objects to encrypt, evaluate, and decrypt ciphertext, without having to write to the local filesystem, thus I need to create a file-like object to store elsewhere. Similarly to this end this will involve serialisation and desirialisation, probably from pickle, which currentley does not work with the pybin11 bindings here. This also prevents things like python deep-copying any of the tenseal objects which is necessary under certain use cases like several workers copying from the same object to evaluate/ compute some function.

## What alternatives have you considered?
Saving to a file and loading that file to a database; time consuming, IO intensive, bottlenecked, and not easily scalable.

## Additional Context
Here is a unit test showcasing the current inability to pickle, and deep-copy, unless I am misunderstanding how it is to be done here:
``test.py``
```
import copy
import unittest


class seal_tests(unittest.TestCase):
    """Unit test class aggregating all tests for the seal class."""

    def get_context_bfv(self):
        import tenseal as ts
        context = ts.context(ts.SCHEME_TYPE.BFV, poly_modulus_degree=4096,
                             plain_modulus=1032193)
        return context

    def test_copy_context_bfv(self):
        context = self.get_context_bfv()
        copy.deepcopy(context)

    def get_keys_bfv(self):
        context = self.get_context_bfv()
        sk = context.secret_key()
        return (context, sk)

    def test_copy_keys_bfv(self):
        context, sk = self.get_keys_bfv()
        copy.deepcopy(sk)

    def get_ciphertext(self):
        import tenseal as ts
        context = self.get_context_bfv()
        plain_vector = [60, 66, 73, 81, 90]
        encrypted_vector = ts.bfv_vector(context, plain_vector)
        return encrypted_vector

    def test_copy_ciphertext(self):
        ciphertext = self.get_ciphertext()
        copy.deepcopy(ciphertext)


if __name__ == "__main__":
    # run all the unit-tests
    unittest.main()
```
when run ``python3 ./test.py``
```
EEE
======================================================================
ERROR: test_copy_ciphertext (__main__.seal_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 36, in test_copy_ciphertext
    copy.deepcopy(ciphertext)
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_tenseal_cpp.BFVVector' object

======================================================================
ERROR: test_copy_context_bfv (__main__.seal_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 16, in test_copy_context_bfv
    copy.deepcopy(context)
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_tenseal_cpp.TenSEALContext' object

======================================================================
ERROR: test_copy_keys_bfv (__main__.seal_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 25, in test_copy_keys_bfv
    copy.deepcopy(sk)
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_tenseal_cpp.SecretKey' object

----------------------------------------------------------------------
Ran 3 tests in 0.048s

FAILED (errors=3)

```

**Comment by youben11** [comment]
We also believe that this is a vital feature to have, we aim at providing serialization ASAP, but this requires planning a serialization strategy and a discussion around different possibilities like the ones you mentioned above, which is something that we can't start in the following days, but definitely an upcoming feature.

**Comment by DreamingRaven** [comment]
Cheers, thanks for the lightning quick response. 
Glad to hear it was already on your minds, im trying to forward FHE even if only slightly in whatever way I can with my limited pybind know-how. Let me know if there is a good way to further this, as I have seen multiple projects battling this very issue, especially with seals (I believe 3.4.5+) changes to serialization.

**Comment by youben11** [comment]
Our serialization would extend SEAL's serialization but we should also setup a strategy for our TenSEALContext as it can contain different object at a certain time, other more simple objects like CKKSVector are pretty straightforward. I haven't digged into the details but I guess there is an issue as well regarding dealing with file-like objects on both python and cpp worlds.

FYI, you can expect serialization to be implemented lately during July.

**Comment by DreamingRaven** [comment]
Thanks @youben11 for letting me know. I will leave this issue open for now/ for anything further relating to this. Cheers.

**Comment by youben11** [comment]
Thanks @DreamingRaven for your inputs

**Comment by bcebere** [comment]
I will work on this one

**Comment by DreamingRaven** [comment]
While hacky I have created pseudo serialisation and deserialisation here primarily for CKKS: 

https://github.com/DreamingRaven/python-reseal/blob/39f6b250d18d62cbff1b185a10d52f12eac316e9/fhe/reseal.py#L24-L77

and I use them in a meta object here: https://github.com/DreamingRaven/python-reseal/blob/39f6b250d18d62cbff1b185a10d52f12eac316e9/fhe/reseal.py#L173-L232 

this allows me to do everything I need, including saving the serialised intermediates to databases deep copying etc. However since it uses file intermediaries from SEAL its a complete hack. But it may give some semblance of help I hope.

**Comment by DreamingRaven** [comment]
The key thing I have found from doing this is that we don't need to make everything serialisable, only the primitives, parameters, ciphertext and keys. The rest can be regenerated on the fly as you can see in the above mentioned meta object ReSeal

**Comment by youben11** [comment]
@DreamingRaven Bogdan just made TenSEAL context serializable using pickle. Whenever we add the feature for serializing CKKSVector then we will be able to implement client/server apps! 

Please let us know how you feel about it :)

**Comment by DreamingRaven** [comment]
@youben11  thanks for letting me know.  I will give context serialization when I get back to my desk and let you know if there are any issues.. 

Hopefully this can replace my existing workaround in my research, which would be amazing. 

I don't think its going to be very long before we start seeing FHE more and more in the field to start tackling very sensitive mostly untouched data. Its just a shame I wish I could find a way to add bootstrapping to MS-SEAL  for arbitrary depth computation albeit with added noise, as that I believe is the big barrier for many libraries to be used in encrypted deep learning as a service applications.

**Comment by youben11** [comment]
Indeed bootstrapping can let us compute circuits of arbitrary depth, however, its computation cost is still impractical as far as I know. Many research have been focusing on the use of Leveled-HE with optimized circuits and batching for implementing practical use cases.

Looking forward for your feedback on serialization!

**Comment by DreamingRaven** [comment]
Hey apologies for the delay. I tried out the same test file from my initial post to see if the context was now serialisable and deserialisable in python. However I have been having some issues with this:

I still get:
```
ERROR: test_copy_context_bfv (__main__.seal_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 16, in test_copy_context_bfv
    copy.deepcopy(context)
  File "/usr/local/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_tenseal_cpp.TenSEALContext' object

```
im not sure if I have missed something with this, I will need to take a closer look to find out why. I am running from inside the latest openmined/tenseal docker container, I presume that is kept up to date with master.
I will try building the container next to double check.

**Comment by youben11** [comment]
latest seems to be attached to the last release which doesn't have the serialization feature, we will look further why it's the case. By the mean time, you can use the one with latest-py38 tag, which is up to date with master.

**Comment by DreamingRaven** [comment]
Hey @youben11 serialisation test (for context) has passed by building from master, so yeah cant see any immediate problems with that.

On a related note, I suspect that the documentation and Dockerfiles are from different times, as the documentation says:

```
Use Docker
You can use our Docker image for a ready to use environment with TenSEAL installed

$ docker container run --interactive --tty openmined/tenseal
You can also build your custom image, this might be handy for developers working on the project

$ docker image build --tag tenseal .
```
However that last command does not use the -f flag to specify the dockerfile name since they are not named exactly "Dockerfile" and rather Dockerfile-py3x such as:
```
docker build -t archer/tenseal . -f Dockerfile-py38
```

Also I noted the dockerfiles attempt to copy the current directory into the containers however since they are in a subdirectory all that will be copied if one changes directory to run them will be the dockerfiles themselves and failing to build. I presume they were moved into a subdirectory after the documentation was written. To my undertstanding the docker context only reaches into subdirectories and not parent directories meaning either the dockerfiles need to be moved to the parent directory or need to be called with the context being in the top level directory of the project (of which I am not to certain of the specific command).

So as a quick fix so I could test I just copied one to the parent directory and ran the following from the same directory:
```
docker build -t archer/tenseal . -f Dockerfile-py38 && docker run -it archer/tenseal
```

**Comment by DreamingRaven** [comment]
Actually I may draft a pull request to use a more normal top level Dockerfile, .dockerignore, and docker-compose; to see if you prefer that to the current setup. Although its not a huge issue either way, it just might throw some people who don't necessarily use docker a lot.

**Comment by philomath213** [comment]
Thank you @DreamingRaven for your notes, as @youben11 said, the `latest` tag is attached to the latest release (v0.1.0) with python 3.8.
If you want to use the image that is attached to the master branch you can use `latest-py38` tag.
Regarding the documentation on building docker image, it's kinda outdated, the instruction should be:
`docker image build --tag tenseal -f docker-images/Dockerfile-py38 .`
Make sure to run the commend withing the repository root directory, otherwise you should specify the building context path
Example, if the working directory is docker-images the building context path should be `..` : 
`docker image build --tag tenseal -f Dockerfile-py38 ..`

**Comment by DreamingRaven** [comment]
Hey @philomath213 I created a minor PR https://github.com/OpenMined/TenSEAL/pull/111 just to patch the documentation, to use the new command similar to the one you listed. I also took the liberty of adding a .dockerignore for good practice.

**Comment by DreamingRaven** [comment]
Let me know when there is any progress on serialization of keys and ciphertext, I will create a unittest PR at some point too, to test this functionality. And thanks for progressing this guys.

**Comment by youben11** [comment]
Thank you @DreamingRaven ! The PR #109 is under review and should be merged in the following days.

**Comment by lunan0320** [comment]
Well, the same problem as you when I want to share the tenseal CKKS context in some processes in Federated Learning. I guess deep_copy()'s problem is similar.
I solve the problem by write the context into a file, other processes just need to read the context. 
But you need to notice that, the context.serialize() method is public by default. If you want to save the secret key, please set the parameter 'save_secret_key=True' in serialize()
Hope it is useful to you.

**Comment by Ksieber26** [comment]
@lunan0320 Hey, currently struggeling with a similar problem. Do you also use the FL Framework Flower ?
