### ISSUE TITLE
Wrong result when performing dot product with CKKS scheme

### ISSUE THREAD

**Issue by apignet** [OpenMined/TenSEAL#82]
Hi. I am new to TenSEAL, and I have some trouble performing dot product.
I am trying to make a dot product between two encrypted vectors, and the decrypted result is far away from the result expected. However, I am able to perform 9 multiplications and additions with my context parameters.

Am I doing something wrong ? 

I built TenSEAL from source the 4th July

## How to Repro
import tenseal as ts
import numpy as np

context = ts.context(ts.SCHEME_TYPE.CKKS, 16384, coeff_mod_bit_sizes=[60, 40, 40, 40, 40, 40, 40, 40, 40, 40])
context.global_scale = pow(2, 40)
context.generate_galois_keys()

plain_vector = [-1, 0, 9, 6, 90]
vec = np.array(plain_vector)
plain_vector2 = [-1, 3, 2, 3, 0]
vec2 = np.array(plain_vector2)

encrypted_vector = ts.ckks_vector(context, plain_vector)
encrypted_vector2 = ts.ckks_vector(context, plain_vector2)

unencrypted_dot = vec.dot(vec2)
encrypted_dot = encrypted_vector.dot(encrypted_vector)

print("unencrypted dot : " + str(unencrypted_dot))
print("encrypted dot : " + str(encrypted_dot .decrypt()[0]))

output : 

unencrypted dot : 37
encrypted dot : 8212.915956094734

Any advice will be appreciate

**Comment by youben11** [comment]
I guess it's yielding the correct result, you just need to replace your line `encrypted_dot = encrypted_vector.dot(encrypted_vector)` with `encrypted_dot = encrypted_vector.dot(encrypted_vector2)` as you were doing the dot product against itself instead of the second vector.

**Comment by apignet** [comment]
Hm I am a little embarrased 
I am really sorry to have wasted your time
Thanks for your quick answer

**Comment by youben11** [comment]
No worries @apignet :), you are also welcome to join the #lib_tenseal channel in our [Slack Community](https://slack.openmined.org) for quick discussions.
