### ISSUE TITLE
Cpp library for TenSEAL

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#83]
## What?
Provide a Cpp library for TenSEAL.

## Why?

As TenSEAL is mainly engineered to work with python, the Cpp API doesn't look really great for Cpp devs, we can rework it so that it can also be used as a Cpp library, while making sure to keep the python compatibility, the python API should always comes first, but it would be great if we can find a middle ground for both of them.

## Breakdown

- Refactor the Cpp API (while keeping the Python API)
- Provides an easily installable Cpp library

## Additional Context
@bcebere recently #73 built a separate cpp library for doing cpp tests, which gave me the idea that it might be useful to provide users with a separate cpp library.

**Comment by IanQS** [comment]
@youben11 Mind if I try and take this on? I'm not sure how quickly I'll be able to knock this out but given how it is low priority I think it would not matter too much?

**Comment by youben11** [comment]
Cool @IanQS , however, this is a special one, as we want to first draw a strategy on how to proceed. The strategy might include API changes, compatibility with other language (as we may want to expand bindings of TenSEAL to more than Python).

And since it would refactor much of the codebase, I think this issue should take all the time it needs for planning, but executed fast to not block other PR that surely will depends on this, or the refactoring will be dealing with new code changes as they are merged into master.
