### ISSUE TITLE
Automate tests on MacOS and Windows

### ISSUE THREAD

**Issue by youben11** [OpenMined/TenSEAL#88]
## Feature Description
We need to test on all platforms (Linux, MacOS, Windows) on every PR.

## Is your feature request related to a problem?
The build on MacOS and Windows was only ran on release, which made us spot problems on release time, instead of catching them early on every codebase change.

**Comment by ramesht007** [comment]
Hey, @youben11 can I work on this issue

**Comment by youben11** [comment]
Hi @ramesht007! Thank you! Feel free to DM me on slack if you need further information :)
